import { Hono } from "hono";
import { and, desc, eq, ilike, isNull, or } from "drizzle-orm";
import { z } from "zod";
import { fail } from "@kb/shared";
import { db } from "../db/client.ts";
import { aiProviders, aiUsage, instanceSettings, notes, workspaces } from "../db/schema.ts";
import { ok } from "../http.ts";
import { currentUser } from "../lib/session.ts";
import { memberRole } from "../lib/workspace.ts";
import { open, seal, suffix } from "../lib/secrets.ts";
import { askKnowledge,retrieve } from "../lib/knowledge-ai.ts";
import { noteAccess } from "../lib/note-access.ts";
export const aiRoutes=new Hono();
async function ctx(c:Parameters<typeof currentUser>[0],wsId:string){const u=await currentUser(c);if(!u)throw fail("UNAUTHENTICATED","未登录");const role=await memberRole(wsId,u.id);if(!role)throw fail("FORBIDDEN","不是工作区成员");const [inst]=await db.select().from(instanceSettings);const [ws]=await db.select().from(workspaces).where(eq(workspaces.id,wsId));if(!inst?.aiEnabled||!ws?.aiEnabled)throw fail("FORBIDDEN","AI 已关闭");return{u,role,ws};}
aiRoutes.get("/workspaces/:id/ai/provider",async c=>{const {u,role}=await ctx(c,c.req.param("id"));const rows=await db.select().from(aiProviders).where(eq(aiProviders.workspaceId,c.req.param("id"))).orderBy(desc(aiProviders.createdAt));return ok(c,{providers:rows.filter(p=>!p.ownerUserId||p.ownerUserId===u.id).map(p=>({id:p.id,kind:p.kind,baseUrl:p.baseUrl,chatModel:p.chatModel,embeddingModel:p.embeddingModel,keySuffix:suffix(p.apiKey),ownerUserId:p.ownerUserId,enabled:p.enabled,canManage:role==="owner"||role==="admin"||p.ownerUserId===u.id}))});});
aiRoutes.post("/workspaces/:id/ai/provider",async c=>{const {u,role}=await ctx(c,c.req.param("id"));const body=z.object({baseUrl:z.string().url(),chatModel:z.string().min(1),embeddingModel:z.string().optional(),apiKey:z.string().min(1),personal:z.boolean().default(false)}).parse(await c.req.json());if(!body.personal&&role!=="owner"&&role!=="admin")throw fail("FORBIDDEN","只有管理员能配置工作区 Key");const [p]=await db.insert(aiProviders).values({workspaceId:c.req.param("id"),ownerUserId:body.personal?u.id:null,baseUrl:body.baseUrl.replace(/\/$/,""),chatModel:body.chatModel,embeddingModel:body.embeddingModel,apiKey:seal(body.apiKey)}).returning();return ok(c,{id:p.id,keySuffix:suffix(p.apiKey)},201);});
aiRoutes.delete("/ai/providers/:id",async c=>{const u=await currentUser(c);if(!u)throw fail("UNAUTHENTICATED","未登录");const [p]=await db.select().from(aiProviders).where(eq(aiProviders.id,c.req.param("id")));if(!p)throw fail("NOT_FOUND","配置不存在");const role=await memberRole(p.workspaceId,u.id);if(p.ownerUserId!==u.id&&role!=="owner"&&role!=="admin")throw fail("FORBIDDEN","无权删除");await db.delete(aiProviders).where(eq(aiProviders.id,p.id));return ok(c,{});});
async function provider(wsId:string,userId:string){const rows=await db.select().from(aiProviders).where(and(eq(aiProviders.workspaceId,wsId),eq(aiProviders.enabled,true))).orderBy(desc(aiProviders.createdAt));return rows.find(p=>p.ownerUserId===userId)??rows.find(p=>!p.ownerUserId);}
async function chat(p:typeof aiProviders.$inferSelect,messages:Array<{role:string;content:string}>){const r=await fetch(`${p.baseUrl}/chat/completions`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${open(p.apiKey)}`},body:JSON.stringify({model:p.chatModel,messages,temperature:0.2})});if(!r.ok)throw fail("AI_PROVIDER_ERROR",`模型请求失败 (${r.status})`);const d=await r.json() as any;return{content:String(d.choices?.[0]?.message?.content??""),usage:d.usage??{}};}
aiRoutes.post("/ai/write",async c=>{const body=z.object({noteId:z.string().uuid(),expectedVersion:z.number().int().positive(),action:z.enum(["polish","shorten","expand","translate","continue","custom"]),text:z.string().min(1).max(50000),language:z.string().optional(),instruction:z.string().trim().min(1).max(500).optional()}).parse(await c.req.json());const [n]=await db.select().from(notes).where(eq(notes.id,body.noteId));if(!n||n.trashedAt)throw fail("NOT_FOUND","笔记不存在");const {u}=await ctx(c,n.workspaceId);await noteAccess(n.id,u.id,"edit");if(n.version!==body.expectedVersion)throw fail("CONFLICT_VERSION","笔记已被其他操作更新，请刷新后重试");const p=await provider(n.workspaceId,u.id);if(!p)throw fail("AI_NOT_CONFIGURED","请先配置 AI 提供商");const instruction={polish:"润色以下文字，保持原意，只输出结果",shorten:"缩短以下文字，只输出结果",expand:"扩写以下文字，只输出结果",translate:`翻译成${body.language??"中文"}，只输出结果`,continue:"续写以下文字，只输出续写内容",custom:`${body.instruction??""}。只输出改写后的正文，不要解释`}[body.action];if(body.action==="custom"&&!body.instruction)throw fail("VALIDATION","自定义指令不能为空");const out=await chat(p,[{role:"system",content:"你是知识库写作助手。禁止输出可执行 HTML。"},{role:"user",content:`${instruction}\n\n${body.text}`}]);await db.insert(aiUsage).values({userId:u.id,workspaceId:n.workspaceId,action:`write:${body.action}`,model:p.chatModel,inputTokens:out.usage.prompt_tokens??0,outputTokens:out.usage.completion_tokens??0});return ok(c,{text:out.content,baseVersion:n.version});});
aiRoutes.post("/ai/search",async c=>{const body=z.object({workspaceId:z.string().uuid(),query:z.string().min(1).max(2000),notebookId:z.string().uuid().optional(),mode:z.enum(["keyword","semantic","hybrid"]).default("hybrid"),limit:z.number().int().min(1).max(20).default(20)}).parse(await c.req.json());const{u}=await ctx(c,body.workspaceId);return ok(c,{hits:await retrieve({...body,userId:u.id})});});
aiRoutes.post("/ai/ask",async c=>{const body=z.object({workspaceId:z.string().uuid(),question:z.string().min(1).max(2000),notebookId:z.string().uuid().optional()}).parse(await c.req.json());const{u}=await ctx(c,body.workspaceId);return ok(c,await askKnowledge({...body,userId:u.id}));});
