import { Hono } from "hono";
import { and,eq,ilike,isNull,or,sql } from "drizzle-orm";
import { z } from "zod";
import { fail } from "@kb/shared";
import { db } from "../db/client.ts";
import { auditLogs,folders,links,mcpDailyUsage,mcpTokens,notebooks,notes,noteVersions,users,workspaces } from "../db/schema.ts";
import { ok } from "../http.ts";import { currentUser } from "../lib/session.ts";import { secureToken,tokenHash } from "../lib/tokens.ts";import { memberRole } from "../lib/workspace.ts";import { writeNoteFile } from "../lib/files.ts";import { rebuildLinks } from "../lib/links.ts";import { assertUserStorage,textBytes } from "../lib/quota.ts";import { limit } from "../lib/rate-limit.ts";import { noteAccess } from "../lib/note-access.ts";import { askKnowledge } from "../lib/knowledge-ai.ts";import { notebookAccess } from "../lib/notebook-access.ts";
export const mcpRoutes=new Hono();
async function user(c:Parameters<typeof currentUser>[0]){const u=await currentUser(c);if(!u)throw fail("UNAUTHENTICATED","未登录");return u;}
mcpRoutes.get("/mcp/tokens",async c=>{const u=await user(c);const rows=await db.select().from(mcpTokens).where(eq(mcpTokens.userId,u.id));return ok(c,{tokens:rows.map(({secretHash:_,...x})=>x)});});
mcpRoutes.post("/mcp/tokens",async c=>{const u=await user(c);const b=z.object({name:z.string().min(1).max(80),workspaceId:z.string().uuid(),notebookMode:z.enum(["inherit","allowlist"]).default("inherit"),notebookIds:z.array(z.string().uuid()).default([]),rw:z.enum(["read","write","manage"]),allowDelete:z.boolean().default(false),requireAiIndex:z.boolean().default(true),allowPrivateNotebooks:z.boolean().default(false),dailyWriteLimitBytes:z.number().int().min(1024).max(1073741824).default(10485760),expiresInDays:z.number().int().min(1).max(365).nullable().optional()}).parse(await c.req.json());const role=await memberRole(b.workspaceId,u.id);if(!role)throw fail("FORBIDDEN","不是工作区成员");if(role==="viewer"&&b.rw!=="read")throw fail("FORBIDDEN","Viewer 只能创建只读钥匙");if(b.allowDelete&&b.rw!=="manage")throw fail("VALIDATION","只有管理钥匙可允许删除");for(const id of b.notebookIds)await notebookAccess(id,u.id,b.rw==="read"?"read":"edit");const id=crypto.randomUUID(),secret=`kbk_${id.slice(0,8)}_${secureToken(24)}`;await db.insert(mcpTokens).values({id,secretHash:tokenHash(secret),name:b.name,userId:u.id,workspaceId:b.workspaceId,notebookMode:b.notebookMode,notebookIds:b.notebookIds,rw:b.rw,allowDelete:b.allowDelete,requireAiIndex:b.requireAiIndex,allowPrivateNotebooks:b.allowPrivateNotebooks,dailyWriteLimitBytes:b.dailyWriteLimitBytes,expiresAt:b.expiresInDays?new Date(Date.now()+b.expiresInDays*86400000):null});return ok(c,{id,secret,config:{mcpServers:{knowledge:{url:`${new URL(c.req.url).origin}/api/v1/mcp`,headers:{Authorization:`Bearer ${secret}`}}}}},201);});
mcpRoutes.post("/mcp/tokens/:id/rotate",async c=>{const u=await user(c);const[old]=await db.select().from(mcpTokens).where(and(eq(mcpTokens.id,c.req.param("id")),eq(mcpTokens.userId,u.id)));if(!old||old.status!=="active")throw fail("NOT_FOUND","钥匙不存在");const id=crypto.randomUUID(),secret=`kbk_${id.slice(0,8)}_${secureToken(24)}`;await db.transaction(async tx=>{await tx.update(mcpTokens).set({status:"revoked"}).where(eq(mcpTokens.id,old.id));await tx.insert(mcpTokens).values({...old,id,secretHash:tokenHash(secret),status:"active",lastUsedAt:null,createdAt:new Date()});});return ok(c,{id,secret},201);});
mcpRoutes.delete("/mcp/tokens/:id",async c=>{const u=await user(c);await db.update(mcpTokens).set({status:"revoked"}).where(and(eq(mcpTokens.id,c.req.param("id")),eq(mcpTokens.userId,u.id)));return ok(c,{});});
type Auth={t:typeof mcpTokens.$inferSelect;u:typeof users.$inferSelect};async function auth(c:any):Promise<Auth>{const bearer=c.req.header("Authorization")?.match(/^Bearer (.+)$/)?.[1];if(!bearer)throw fail("UNAUTHENTICATED","缺少 Bearer token");const[t]=await db.select().from(mcpTokens).where(eq(mcpTokens.secretHash,tokenHash(bearer)));if(!t||t.status!=="active"||(t.expiresAt&&t.expiresAt<=new Date()))throw fail("UNAUTHENTICATED","MCP 钥匙无效");const[u]=await db.select().from(users).where(eq(users.id,t.userId));if(!u||u.status!=="active"||!await memberRole(t.workspaceId,u.id))throw fail("FORBIDDEN","用户或成员资格不可用");if(!limit(`mcp:${t.id}`,120,60000))throw fail("RATE_LIMIT","请求过于频繁");await db.update(mcpTokens).set({lastUsedAt:new Date()}).where(eq(mcpTokens.id,t.id));return{t,u};}
function inScope(a:Auth,notebookId:string){return a.t.notebookMode!=="allowlist"||(a.t.notebookIds as string[]).includes(notebookId);}async function nbPermission(a:Auth,id:string,mode:"read"|"edit"){if(!inScope(a,id))throw fail("FORBIDDEN","笔记本不在钥匙范围");const x=await notebookAccess(id,a.u.id,mode);if(x.workspace.id!==a.t.workspaceId)throw fail("FORBIDDEN","跨工作区访问");if(x.notebook.visibility==="private"&&!a.t.allowPrivateNotebooks)throw fail("FORBIDDEN","钥匙不允许私密笔记本");return x;}async function permission(a:Auth,id:string,mode:"read"|"edit"="read"){const x=await noteAccess(id,a.u.id,mode);if(x.workspace.id!==a.t.workspaceId||!inScope(a,x.notebook.id))throw fail("FORBIDDEN","笔记不在钥匙范围");if(x.notebook.visibility==="private"&&!a.t.allowPrivateNotebooks)throw fail("FORBIDDEN","钥匙不允许私密笔记本");if(mode==="read"&&a.t.requireAiIndex&&!x.note.aiIndex)throw fail("FORBIDDEN","笔记未启用 AI 索引");return x;}
function requireWrite(a:Auth,manage=false){if(a.t.rw==="read"||(manage&&a.t.rw!=="manage"))throw fail("FORBIDDEN",manage?"需要 manage 权限":"钥匙只读");}async function charge(a:Auth,bytes:number){const day=new Date().toISOString().slice(0,10);const rows=await db.execute(sql`INSERT INTO mcp_daily_usage(token_id,day,write_bytes) VALUES(${a.t.id},${day},${bytes}) ON CONFLICT(token_id,day) DO UPDATE SET write_bytes=mcp_daily_usage.write_bytes+${bytes} WHERE mcp_daily_usage.write_bytes+${bytes}<=${a.t.dailyWriteLimitBytes} RETURNING write_bytes`);if(!rows.length)throw fail("RATE_LIMIT","已达到 MCP 每日写入字节额度");}
const tools=["get_me","list_notebooks","list_folder","search_notes","get_note","get_backlinks","ask_knowledge","create_note","update_note","append_to_note","move_note","add_tags","trash_note"].map(name=>({name,inputSchema:{type:"object"}}));
mcpRoutes.post("/mcp",async c=>{let a:Auth|undefined,name="",id:any=null;try{a=await auth(c);const body=z.object({jsonrpc:z.literal("2.0"),id:z.any().optional(),method:z.string(),params:z.any().optional()}).parse(await c.req.json());id=body.id??null;if(body.method==="initialize")return c.json({jsonrpc:"2.0",id,result:{protocolVersion:"2025-03-26",capabilities:{tools:{}},serverInfo:{name:"knowledge-brain",version:"1.0.0"}}});if(body.method==="notifications/initialized")return c.body(null,204);if(body.method==="tools/list")return c.json({jsonrpc:"2.0",id,result:{tools}});if(body.method!=="tools/call")throw fail("VALIDATION","不支持的方法");name=String(body.params?.name??"");const x=body.params?.arguments??{};let result:any;
if(name==="get_me"){const[ws]=await db.select().from(workspaces).where(eq(workspaces.id,a.t.workspaceId));result={handle:a.u.handle,workspace:{id:ws.id,name:ws.name},rw:a.t.rw,notebook_mode:a.t.notebookMode,expires_at:a.t.expiresAt};}
else if(name==="list_notebooks"){const rows=await db.select().from(notebooks).where(and(eq(notebooks.workspaceId,a.t.workspaceId),isNull(notebooks.trashedAt)));result=[];for(const nb of rows)try{await nbPermission(a,nb.id,"read");result.push({id:nb.id,title:nb.title,visibility:nb.visibility});}catch{}}
else if(name==="list_folder"){const b=z.object({notebook_id:z.string().uuid(),folder_id:z.string().uuid().nullable().optional()}).parse(x);await nbPermission(a,b.notebook_id,"read");const fs=await db.select().from(folders).where(and(eq(folders.notebookId,b.notebook_id),isNull(folders.trashedAt)));const ns=await db.select().from(notes).where(and(eq(notes.notebookId,b.notebook_id),isNull(notes.trashedAt)));result={folders:fs.filter(f=>(f.parentId??null)===(b.folder_id??null)).map(f=>({id:f.id,title:f.title})),notes:ns.filter(n=>(n.folderId??null)===(b.folder_id??null)&&(!a!.t.requireAiIndex||n.aiIndex)).map(n=>({id:n.id,title:n.title}))};}
else if(name==="search_notes"){const b=z.object({query:z.string().min(1),notebook_id:z.string().uuid().optional(),tag:z.string().optional(),limit:z.number().int().min(1).max(20).default(20)}).parse(x);if(b.notebook_id)await nbPermission(a,b.notebook_id,"read");const rows=await db.select().from(notes).where(and(eq(notes.workspaceId,a.t.workspaceId),isNull(notes.trashedAt),or(ilike(notes.title,`%${b.query}%`),ilike(notes.bodyMd,`%${b.query}%`))));result=[];for(const n of rows)try{await permission(a,n.id);if(!b.notebook_id||n.notebookId===b.notebook_id){const tags=n.tags as string[];if(!b.tag||tags.includes(b.tag))result.push({id:n.id,title:n.title,snippet:n.bodyMd.slice(0,240),tags});}if(result.length>=b.limit)break;}catch{}}
else if(name==="get_note"){const b=z.object({id:z.string().uuid()}).parse(x),{note:n}=await permission(a,b.id);const ls=await db.select().from(links).where(eq(links.fromNoteId,n.id));result={id:n.id,title:n.title,body_md:n.bodyMd,version:n.version,tags:n.tags,ai_index:n.aiIndex,published:n.published,links:ls};}
else if(name==="get_backlinks"){const b=z.object({id:z.string().uuid()}).parse(x);await permission(a,b.id);const rows=await db.select().from(links).where(eq(links.targetNoteId,b.id));result=[];for(const l of rows)try{const{note:n}=await permission(a,l.fromNoteId);result.push({id:n.id,title:n.title,snippet:n.bodyMd.slice(0,240)});}catch{}}
else if(name==="ask_knowledge"){const b=z.object({question:z.string().min(1).max(2000),notebook_id:z.string().uuid().optional()}).parse(x);if(b.notebook_id)await nbPermission(a,b.notebook_id,"read");result=await askKnowledge({workspaceId:a.t.workspaceId,userId:a.u.id,question:b.question,notebookId:b.notebook_id});}
else if(name==="create_note"){requireWrite(a);const b=z.object({notebook_id:z.string().uuid(),folder_id:z.string().uuid().nullable().optional(),title:z.string().min(1).max(200),content:z.string().default(""),tags:z.array(z.string().min(1).max(50)).max(50).default([])}).parse(x),{notebook:nb}=await nbPermission(a,b.notebook_id,"edit");if(b.folder_id){const[f]=await db.select().from(folders).where(and(eq(folders.id,b.folder_id),eq(folders.notebookId,nb.id),isNull(folders.trashedAt)));if(!f)throw fail("VALIDATION","目录不属于目标笔记本");}await charge(a,textBytes(b.title,b.content));await assertUserStorage(a.u.id,textBytes(b.title,b.content));const[n]=await db.insert(notes).values({workspaceId:a.t.workspaceId,notebookId:nb.id,folderId:b.folder_id??null,title:b.title,bodyMd:b.content,tags:b.tags,aiIndex:nb.defaultAiIndex,createdBy:a.u.id,updatedBy:a.u.id}).returning();await writeNoteFile({...n,noteId:n.id,bodyMd:n.bodyMd});await rebuildLinks(n.id,n.workspaceId,n.bodyMd);result={id:n.id,version:n.version};}
else if(name==="update_note"||name==="append_to_note"){requireWrite(a);const b=z.object({id:z.string().uuid(),expected_version:z.number().int().positive().optional(),content:z.string().optional(),title:z.string().min(1).max(200).optional()}).parse(x),{note:n}=await permission(a,b.id,"edit");if(name==="update_note"&&b.expected_version===undefined)throw fail("VALIDATION","expected_version 必填");if(b.expected_version!==undefined&&b.expected_version!==n.version)throw fail("CONFLICT_VERSION","版本冲突");const title=b.title??n.title,bodyMd=name==="append_to_note"?`${n.bodyMd}${n.bodyMd?"\n":""}${b.content??""}`:b.content??n.bodyMd;const delta=Math.max(0,textBytes(title,bodyMd)-textBytes(n.title,n.bodyMd));await charge(a,Buffer.byteLength(b.content??"","utf8")+Buffer.byteLength(b.title??"","utf8"));await assertUserStorage(n.createdBy,delta);const[saved]=await db.transaction(async tx=>{await tx.insert(noteVersions).values({noteId:n.id,version:n.version,title:n.title,bodyMd:n.bodyMd,editorId:a!.u.id,source:"mcp"});return tx.update(notes).set({title,bodyMd,version:n.version+1,updatedBy:a!.u.id,updatedAt:new Date()}).where(and(eq(notes.id,n.id),eq(notes.version,n.version))).returning();});if(!saved)throw fail("CONFLICT_VERSION","版本冲突");await writeNoteFile({...saved,noteId:saved.id,bodyMd:saved.bodyMd});await rebuildLinks(saved.id,saved.workspaceId,saved.bodyMd);result={id:saved.id,version:saved.version};}
else if(name==="move_note"){requireWrite(a,true);const b=z.object({id:z.string().uuid(),notebook_id:z.string().uuid(),folder_id:z.string().uuid().nullable().optional()}).parse(x),{note:n}=await permission(a,b.id,"edit"),{notebook:nb}=await nbPermission(a,b.notebook_id,"edit");if(b.folder_id){const[f]=await db.select().from(folders).where(and(eq(folders.id,b.folder_id),eq(folders.notebookId,nb.id),isNull(folders.trashedAt)));if(!f)throw fail("VALIDATION","目录不属于目标笔记本");}const[saved]=await db.update(notes).set({notebookId:nb.id,folderId:b.folder_id??null,version:n.version+1,updatedBy:a.u.id,updatedAt:new Date()}).where(eq(notes.id,n.id)).returning();await writeNoteFile({...saved,noteId:saved.id,bodyMd:saved.bodyMd});result={id:saved.id,version:saved.version};}
else if(name==="add_tags"){requireWrite(a,true);const b=z.object({id:z.string().uuid(),tags:z.array(z.string().min(1).max(50)).max(50)}).parse(x),{note:n}=await permission(a,b.id,"edit"),merged=[...new Set([...(n.tags as string[]),...b.tags])].slice(0,50);await charge(a,Buffer.byteLength(JSON.stringify(b.tags)));const[saved]=await db.update(notes).set({tags:merged,version:n.version+1,updatedBy:a.u.id,updatedAt:new Date()}).where(eq(notes.id,n.id)).returning();result={id:saved.id,version:saved.version,tags:merged};}
else if(name==="trash_note"){requireWrite(a,true);if(!a.t.allowDelete)throw fail("FORBIDDEN","钥匙未授权删除");const b=z.object({id:z.string().uuid()}).parse(x),{note:n}=await permission(a,b.id,"edit");await db.update(notes).set({trashedAt:new Date(),trashedBy:a.u.id,trashBatchId:crypto.randomUUID()}).where(eq(notes.id,n.id));result={};}else throw fail("VALIDATION","未知工具");await db.insert(auditLogs).values({userId:a.u.id,workspaceId:a.t.workspaceId,actorType:"mcp",actorId:a.t.id,action:`mcp.${name}`,result:"ok",details:{arguments:x}});return c.json({jsonrpc:"2.0",id,result:{content:[{type:"text",text:JSON.stringify(result)}],structuredContent:result}});
}catch(e){if(a)await db.insert(auditLogs).values({userId:a.u.id,workspaceId:a.t.workspaceId,actorType:"mcp",actorId:a.t.id,action:`mcp.${name||"request"}`,result:"error",details:{message:e instanceof Error?e.message:String(e)}});return c.json({jsonrpc:"2.0",id,error:{code:-32000,message:e instanceof Error?e.message:String(e)}});}});
