import { Hono } from "hono";
import { and,count,eq,ilike,inArray,isNull,or,sql } from "drizzle-orm";
import { z } from "zod";
import { AppError, fail } from "@kb/shared";
import { db } from "../db/client.ts";
import { env } from "../env.ts";
import { auditLogs,calendarItems,calendarOverrides,folders,links,mcpDailyUsage,mcpTokens,notebooks,notes,noteVersions,posts,users,workspaces } from "../db/schema.ts";
import { ok } from "../http.ts";import { currentUser } from "../lib/session.ts";import { hashSecret,secretHashes,secureToken } from "../lib/tokens.ts";import { memberRole } from "../lib/workspace.ts";import { writeNoteFile } from "../lib/files.ts";import { rebuildLinks } from "../lib/links.ts";import { assertUserStorage,textBytes } from "../lib/quota.ts";import { limit } from "../lib/rate-limit.ts";import { noteAccess } from "../lib/note-access.ts";import { askKnowledge } from "../lib/knowledge-ai.ts";import { notebookAccess } from "../lib/notebook-access.ts";import { completeCalendarItem,DEFAULT_TZ,occurrencesOf,startOfLocalDay } from "../lib/calendar.ts";
export const mcpRoutes=new Hono();
type Ctx=Parameters<typeof currentUser>[0];
async function user(c:Ctx){const u=await currentUser(c);if(!u)throw fail("UNAUTHENTICATED","未登录");return u;}
function mcpConfigs(_c:Ctx,secret:string){const url=`${env.publicUrl}/api/v1/mcp`;return{config:{mcpServers:{knowledge:{url,headers:{Authorization:`Bearer ${secret}`}}}},stdioConfig:{mcpServers:{knowledge:{command:"npx",args:["-y","mcp-remote",url,"--header",`Authorization: Bearer ${secret}`]}}}};}
mcpRoutes.get("/mcp/tokens",async c=>{const u=await user(c);const rows=await db.select().from(mcpTokens).where(eq(mcpTokens.userId,u.id));const list=c.req.query("includeRevoked")==="1"?rows:rows.filter(t=>t.status==="active");return ok(c,{tokens:list.map(({secretHash:_,...x})=>x)});});
mcpRoutes.post("/mcp/tokens",async c=>{const u=await user(c);const b=z.object({name:z.string().min(1).max(80),workspaceId:z.string().uuid(),notebookMode:z.enum(["inherit","allowlist"]).default("inherit"),notebookIds:z.array(z.string().uuid()).default([]),rw:z.enum(["read","write","manage"]),allowDelete:z.boolean().default(false),requireAiIndex:z.boolean().default(true),allowPrivateNotebooks:z.boolean().default(false),feedPublic:z.boolean().default(false),feedWorkspace:z.boolean().default(false),dailyWriteLimitBytes:z.number().int().min(1024).max(1073741824).nullable().default(null),expiresInDays:z.number().int().min(1).max(365).nullable().optional()}).parse(await c.req.json());const role=await memberRole(b.workspaceId,u.id);if(!role)throw fail("FORBIDDEN","不是工作区成员");if(role==="viewer"&&b.rw!=="read")throw fail("FORBIDDEN","Viewer 只能创建只读钥匙");if(b.allowDelete&&b.rw!=="manage")throw fail("VALIDATION","只有管理钥匙可允许删除");for(const id of b.notebookIds)await notebookAccess(id,u.id,b.rw==="read"?"read":"edit");const id=crypto.randomUUID(),secret=`kbk_${id.slice(0,8)}_${secureToken(24)}`;await db.insert(mcpTokens).values({id,secretHash:hashSecret(secret),name:b.name,userId:u.id,workspaceId:b.workspaceId,notebookMode:b.notebookMode,notebookIds:b.notebookIds,rw:b.rw,allowDelete:b.allowDelete,requireAiIndex:b.requireAiIndex,allowPrivateNotebooks:b.allowPrivateNotebooks,feedPublic:b.feedPublic,feedWorkspace:b.feedWorkspace,dailyWriteLimitBytes:b.dailyWriteLimitBytes,expiresAt:b.expiresInDays?new Date(Date.now()+b.expiresInDays*86400000):null});return ok(c,{id,secret,...mcpConfigs(c,secret)},201);});
mcpRoutes.post("/mcp/tokens/:id/rotate",async c=>{const u=await user(c);const[old]=await db.select().from(mcpTokens).where(and(eq(mcpTokens.id,c.req.param("id")),eq(mcpTokens.userId,u.id)));if(!old||old.status!=="active")throw fail("NOT_FOUND","钥匙不存在");const id=crypto.randomUUID(),secret=`kbk_${id.slice(0,8)}_${secureToken(24)}`;await db.transaction(async tx=>{await tx.update(mcpTokens).set({status:"revoked"}).where(eq(mcpTokens.id,old.id));await tx.insert(mcpTokens).values({...old,id,secretHash:hashSecret(secret),status:"active",lastUsedAt:null,createdAt:new Date()});});return ok(c,{id,secret,...mcpConfigs(c,secret)},201);});
mcpRoutes.patch("/mcp/tokens/:id",async c=>{const u=await user(c);const[t]=await db.select().from(mcpTokens).where(and(eq(mcpTokens.id,c.req.param("id")),eq(mcpTokens.userId,u.id)));if(!t||t.status!=="active")throw fail("NOT_FOUND","钥匙不存在");const b=z.object({name:z.string().min(1).max(80).optional(),notebookMode:z.enum(["inherit","allowlist"]).optional(),notebookIds:z.array(z.string().uuid()).optional(),rw:z.enum(["read","write","manage"]).optional(),allowDelete:z.boolean().optional(),requireAiIndex:z.boolean().optional(),allowPrivateNotebooks:z.boolean().optional(),feedPublic:z.boolean().optional(),feedWorkspace:z.boolean().optional(),dailyWriteLimitBytes:z.number().int().min(1024).max(1073741824).nullable().optional(),expiresInDays:z.number().int().min(1).max(365).nullable().optional()}).parse(await c.req.json());const rw=b.rw??t.rw,allowDelete=b.allowDelete??t.allowDelete,mode=b.notebookMode??t.notebookMode,notebookIds=b.notebookIds??(t.notebookIds as string[]);const role=await memberRole(t.workspaceId,u.id);if(!role)throw fail("FORBIDDEN","不是工作区成员");if(role==="viewer"&&rw!=="read")throw fail("FORBIDDEN","Viewer 只能持有只读钥匙");if(allowDelete&&rw!=="manage")throw fail("VALIDATION","只有管理钥匙可允许删除");if(mode==="allowlist")for(const id of notebookIds)await notebookAccess(id,u.id,rw==="read"?"read":"edit");await db.update(mcpTokens).set({...(b.name!==undefined?{name:b.name}:{}),notebookMode:mode,notebookIds,rw,allowDelete,...(b.requireAiIndex!==undefined?{requireAiIndex:b.requireAiIndex}:{}),...(b.allowPrivateNotebooks!==undefined?{allowPrivateNotebooks:b.allowPrivateNotebooks}:{}),...(b.feedPublic!==undefined?{feedPublic:b.feedPublic}:{}),...(b.feedWorkspace!==undefined?{feedWorkspace:b.feedWorkspace}:{}),...(b.dailyWriteLimitBytes!==undefined?{dailyWriteLimitBytes:b.dailyWriteLimitBytes}:{}),...(b.expiresInDays!==undefined?{expiresAt:b.expiresInDays?new Date(Date.now()+b.expiresInDays*86400000):null}:{})}).where(eq(mcpTokens.id,t.id));return ok(c,{});});
mcpRoutes.delete("/mcp/tokens/:id",async c=>{const u=await user(c);await db.update(mcpTokens).set({status:"revoked"}).where(and(eq(mcpTokens.id,c.req.param("id")),eq(mcpTokens.userId,u.id)));return ok(c,{});});
type Auth={t:typeof mcpTokens.$inferSelect;u:typeof users.$inferSelect};async function auth(c:Ctx):Promise<Auth>{const bearer=c.req.header("Authorization")?.match(/^Bearer (.+)$/)?.[1];if(!bearer)throw fail("UNAUTHENTICATED","缺少 Bearer token");const[t]=await db.select().from(mcpTokens).where(inArray(mcpTokens.secretHash,secretHashes(bearer)));if(!t||t.status!=="active"||(t.expiresAt&&t.expiresAt<=new Date()))throw fail("UNAUTHENTICATED","MCP 钥匙无效");const[u]=await db.select().from(users).where(eq(users.id,t.userId));if(!u||u.status!=="active"||!await memberRole(t.workspaceId,u.id))throw fail("FORBIDDEN","用户或成员资格不可用");limit(`mcp:${t.id}`,120,60000);await db.update(mcpTokens).set({lastUsedAt:new Date()}).where(eq(mcpTokens.id,t.id));return{t,u};}
function inScope(a:Auth,notebookId:string){return a.t.notebookMode!=="allowlist"||(a.t.notebookIds as string[]).includes(notebookId);}async function nbPermission(a:Auth,id:string,mode:"read"|"edit"){if(!inScope(a,id))throw fail("FORBIDDEN","笔记本不在钥匙范围");const x=await notebookAccess(id,a.u.id,mode);if(x.workspace.id!==a.t.workspaceId)throw fail("FORBIDDEN","跨工作区访问");if(x.notebook.visibility==="private"&&!a.t.allowPrivateNotebooks)throw fail("FORBIDDEN","钥匙不允许私密笔记本");return x;}async function permission(a:Auth,id:string,mode:"read"|"edit"="read"){const x=await noteAccess(id,a.u.id,mode);if(x.workspace.id!==a.t.workspaceId||!inScope(a,x.notebook.id))throw fail("FORBIDDEN","笔记不在钥匙范围");if(x.notebook.visibility==="private"&&!a.t.allowPrivateNotebooks)throw fail("FORBIDDEN","钥匙不允许私密笔记本");if(mode==="read"&&a.t.requireAiIndex&&!x.note.aiIndex)throw fail("FORBIDDEN","笔记未启用 AI 索引");return x;}
function requireWrite(a:Auth,manage=false){if(a.t.rw==="read"||(manage&&a.t.rw!=="manage"))throw fail("FORBIDDEN",manage?"需要 manage 权限":"钥匙只读");}async function charge(a:Auth,bytes:number){const day=new Date().toISOString().slice(0,10),cap=a.t.dailyWriteLimitBytes;const rows=await db.execute(cap==null?sql`INSERT INTO mcp_daily_usage(token_id,day,write_bytes) VALUES(${a.t.id},${day},${bytes}) ON CONFLICT(token_id,day) DO UPDATE SET write_bytes=mcp_daily_usage.write_bytes+${bytes} RETURNING write_bytes`:sql`INSERT INTO mcp_daily_usage(token_id,day,write_bytes) VALUES(${a.t.id},${day},${bytes}) ON CONFLICT(token_id,day) DO UPDATE SET write_bytes=mcp_daily_usage.write_bytes+${bytes} WHERE mcp_daily_usage.write_bytes+${bytes}<=${cap} RETURNING write_bytes`);if(!rows.length)throw fail("QUOTA","已达到 MCP 每日写入字节额度");}
/** 日历条目的可见性：来自笔记的完全继承笔记（连钥匙的笔记本范围、ai_index、私密开关一起继承），其余按 visibility。 */
async function visibleCalendarItems(a:Auth,rows:Array<typeof calendarItems.$inferSelect>){const out:Array<typeof calendarItems.$inferSelect>=[];for(const r of rows){if(r.source==="note"&&r.sourceNoteId){try{await permission(a,r.sourceNoteId);}catch{continue;}}else if(r.visibility==="private"&&r.createdBy!==a.u.id)continue;out.push(r);}return out;}
/** 客户端若没拿到 inputSchema（比如缓存着旧的空 schema），数字与布尔会以字符串发过来。
 *  工具层统一容忍这一种松散写法，别让调用方在类型上翻车。 */
const zint=()=>z.coerce.number().int();
const zbool=()=>z.union([z.boolean(),z.enum(["true","false"]).transform(v=>v==="true")]);
const baseTools=["get_me","list_notebooks","list_folder","search_notes","get_note","get_backlinks","ask_knowledge","create_note","update_note","append_to_note","move_note","add_tags","trash_note","list_tasks","list_events","create_task","complete_task"];
/** tools/list 必须给出真实的参数表：客户端只有拿到 properties 才知道字段名与类型，
 *  否则数字会被当成字符串发过来（expected_version 就踩过这个坑）。 */
const UUID={type:"string",format:"uuid"} as const;
const NUL_UUID={type:["string","null"],format:"uuid"} as const;
const TAGS={type:"array",items:{type:"string",minLength:1,maxLength:50},maxItems:50} as const;
const EDIT_PROPS={id:UUID,expected_version:{type:"integer",minimum:1},content:{type:"string"},title:{type:"string",minLength:1,maxLength:200}} as const;
const TOOL_DEFS:Record<string,{description:string;properties?:Record<string,unknown>;required?:string[]}>={
 get_me:{description:"返回当前 MCP 钥匙的持有人、工作区、读写档与到期时间。"},
 list_notebooks:{description:"列出这把钥匙范围内的笔记本。"},
 list_folder:{description:"列出某个笔记本或目录下的子目录与笔记；folder_id 省略或传 null 表示根目录。",properties:{notebook_id:UUID,folder_id:NUL_UUID},required:["notebook_id"]},
 search_notes:{description:"全文检索笔记，可按笔记本或标签过滤。",properties:{query:{type:"string",minLength:1},notebook_id:UUID,tag:{type:"string"},limit:{type:"integer",minimum:1,maximum:20,default:20}},required:["query"]},
 get_note:{description:"按 ID 读取笔记的正文、版本号、标签与双链。",properties:{id:UUID},required:["id"]},
 get_backlinks:{description:"列出指向该笔记的反向链接。",properties:{id:UUID},required:["id"]},
 ask_knowledge:{description:"基于知识库内容问答，返回答案与引用来源。",properties:{question:{type:"string",minLength:1,maxLength:2000},notebook_id:UUID},required:["question"]},
 create_note:{description:"新建笔记。",properties:{notebook_id:UUID,folder_id:NUL_UUID,title:{type:"string",minLength:1,maxLength:200},content:{type:"string",default:""},tags:TAGS},required:["notebook_id","title"]},
 update_note:{description:"覆盖笔记正文或标题。expected_version 必填，传 get_note 拿到的 version，版本不符会报 CONFLICT_VERSION。",properties:EDIT_PROPS,required:["id","expected_version"]},
 append_to_note:{description:"在笔记末尾追加内容，不覆盖原文；expected_version 可选，传了就做版本校验。",properties:EDIT_PROPS,required:["id","content"]},
 move_note:{description:"把笔记移动到另一个笔记本或目录。",properties:{id:UUID,notebook_id:UUID,folder_id:NUL_UUID},required:["id","notebook_id"]},
 add_tags:{description:"给笔记追加标签，与原有标签合并去重。",properties:{id:UUID,tags:TAGS},required:["id","tags"]},
 trash_note:{description:"把笔记移入回收站（不是永久删除）。",properties:{id:UUID},required:["id"]},
 post_to_feed:{description:"发一条动态到工作区圈子或公开广场，可带笔记回链。",properties:{body:{type:"string",minLength:1,maxLength:5000},scope:{type:"string",enum:["workspace","public"],default:"workspace"},note_id:UUID},required:["body"]},
 list_tasks:{description:"列出任务，默认只看未完成的。时间是 ISO 8601 字符串。",properties:{from:{type:"string",format:"date-time"},to:{type:"string",format:"date-time"},status:{type:"string",enum:["open","done","all"],default:"open"},assignee:{type:"string",maxLength:40},include_inbox:{type:"boolean",default:true},limit:{type:"integer",minimum:1,maximum:200,default:200}}},
 list_events:{description:"列出日历条目（含任务与事件）。时间是 ISO 8601 字符串。",properties:{from:{type:"string",format:"date-time"},to:{type:"string",format:"date-time"},status:{type:"string",enum:["open","done","all"],default:"all"},assignee:{type:"string",maxLength:40},include_inbox:{type:"boolean",default:true},limit:{type:"integer",minimum:1,maximum:200,default:200}}},
 create_task:{description:"新建任务；due_at 省略或传 null 进收集箱。",properties:{title:{type:"string",minLength:1,maxLength:200},due_at:{type:["string","null"],format:"date-time"},all_day:{type:"boolean",default:false},priority:{type:"integer",minimum:0,maximum:3,default:0},note:{type:"string",maxLength:2000,default:""}},required:["title"]},
 complete_task:{description:"勾选或取消勾选任务；重复任务用 occurrence_start 指定是哪一次。",properties:{id:UUID,done:{type:"boolean",default:true},occurrence_start:{type:"string",format:"date-time"}},required:["id"]},
};
function toolsFor(t:typeof mcpTokens.$inferSelect){const names=[...baseTools];if(t.feedPublic||t.feedWorkspace)names.push("post_to_feed");return names.map(name=>{const d=TOOL_DEFS[name];return{name,description:d?.description??"",inputSchema:{type:"object",properties:d?.properties??{},required:d?.required??[]}};});}
/** 未认证的应答：401 且带 WWW-Authenticate，云端客户端靠它发现授权服务器（RFC 9728）。 */
function unauthorized(c:Ctx,id:unknown,message:string){return c.json({jsonrpc:"2.0",id,error:{code:-32001,message}},401,{"WWW-Authenticate":`Bearer resource_metadata="${env.publicUrl}/.well-known/oauth-protected-resource"`});}
/** Streamable HTTP 的客户端会先 GET 一次，探服务端主动推的那条 SSE 流；会话结束时可能发 DELETE。
 *  这个端点是纯请求-响应，按协议回 405 客户端就认了。以前这两个动词落到 404 上，有的客户端
 *  会把它理解成「端点不存在」而不是「这里没有 SSE」，于是不停重连——看着就像服务不稳定。
 *  没带 token 的探测仍旧回 401，别把发现授权服务器那条路一起堵死。 */
mcpRoutes.on(["GET","DELETE"],"/mcp",c=>c.req.header("Authorization")?c.json({jsonrpc:"2.0",id:null,error:{code:-32000,message:"该端点只接受 POST"}},405,{Allow:"POST"}):unauthorized(c,null,"缺少 Bearer token"));
/** 审计只记「调了什么」，不记正文：一篇笔记已经在 notes 和 note_versions 里各存了一份，
 *  再往 audit_logs 的 jsonb 里塞第三份，批量迁移时库会被撑大好几倍，大 jsonb 的插入
 *  本身也会把这次写请求拖慢。长字符串一律截断，id / 标题这些短字段原样留着。 */
function auditArgs(x:unknown){if(!x||typeof x!=="object"||Array.isArray(x))return x;const out:Record<string,unknown>={};for(const[k,v]of Object.entries(x as Record<string,unknown>))out[k]=typeof v==="string"&&v.length>200?`${v.slice(0,200)}…（共 ${v.length} 字，正文见笔记本身）`:v;return out;}
mcpRoutes.post("/mcp",async c=>{let a:Auth|undefined,name="",id:unknown=null;try{a=await auth(c);const body=z.object({jsonrpc:z.literal("2.0"),id:z.any().optional(),method:z.string(),params:z.any().optional()}).parse(await c.req.json());id=body.id??null;if(body.method==="initialize")return c.json({jsonrpc:"2.0",id,result:{protocolVersion:"2025-03-26",capabilities:{tools:{}},serverInfo:{name:"knowledge-brain",version:"1.0.0"}}});if(body.method==="notifications/initialized")return c.body(null,204);if(body.method==="tools/list")return c.json({jsonrpc:"2.0",id,result:{tools:toolsFor(a.t)}});if(body.method!=="tools/call")throw fail("VALIDATION","不支持的方法");name=String(body.params?.name??"");const x=body.params?.arguments??{};/** MCP 工具的返回值按协议就是任意 JSON：要么是一组条目，要么是一个对象。 */
type ToolResult=Array<Record<string,unknown>>|Record<string,unknown>|undefined;let result:ToolResult;
if(name==="get_me"){const[ws]=await db.select().from(workspaces).where(eq(workspaces.id,a.t.workspaceId));result={handle:a.u.handle,workspace:{id:ws.id,name:ws.name},rw:a.t.rw,notebook_mode:a.t.notebookMode,expires_at:a.t.expiresAt};}
else if(name==="list_notebooks"){const rows=await db.select().from(notebooks).where(and(eq(notebooks.workspaceId,a.t.workspaceId),isNull(notebooks.trashedAt)));result=[] as Array<Record<string,unknown>>;for(const nb of rows)try{await nbPermission(a,nb.id,"read");result.push({id:nb.id,title:nb.title,visibility:nb.visibility});}catch{}}
else if(name==="list_folder"){const b=z.object({notebook_id:z.string().uuid(),folder_id:z.string().uuid().nullable().optional()}).parse(x);await nbPermission(a,b.notebook_id,"read");const fs=await db.select().from(folders).where(and(eq(folders.notebookId,b.notebook_id),isNull(folders.trashedAt)));const ns=await db.select().from(notes).where(and(eq(notes.notebookId,b.notebook_id),isNull(notes.trashedAt)));result={folders:fs.filter(f=>(f.parentId??null)===(b.folder_id??null)).map(f=>({id:f.id,title:f.title})),notes:ns.filter(n=>(n.folderId??null)===(b.folder_id??null)&&(!a!.t.requireAiIndex||n.aiIndex)).map(n=>({id:n.id,title:n.title}))};}
else if(name==="search_notes"){const b=z.object({query:z.string().min(1),notebook_id:z.string().uuid().optional(),tag:z.string().optional(),limit:zint().min(1).max(20).default(20)}).parse(x);if(b.notebook_id)await nbPermission(a,b.notebook_id,"read");const rows=await db.select().from(notes).where(and(eq(notes.workspaceId,a.t.workspaceId),isNull(notes.trashedAt),or(ilike(notes.title,`%${b.query}%`),ilike(notes.bodyMd,`%${b.query}%`))));result=[];for(const n of rows)try{await permission(a,n.id);if(!b.notebook_id||n.notebookId===b.notebook_id){const tags=n.tags as string[];if(!b.tag||tags.includes(b.tag))result.push({id:n.id,title:n.title,snippet:n.bodyMd.slice(0,240),tags});}if(result.length>=b.limit)break;}catch{}}
else if(name==="get_note"){const b=z.object({id:z.string().uuid()}).parse(x),{note:n}=await permission(a,b.id);const ls=await db.select().from(links).where(eq(links.fromNoteId,n.id));result={id:n.id,title:n.title,body_md:n.bodyMd,version:n.version,tags:n.tags,ai_index:n.aiIndex,published:n.published,links:ls};}
else if(name==="get_backlinks"){const b=z.object({id:z.string().uuid()}).parse(x);await permission(a,b.id);const rows=await db.select().from(links).where(eq(links.targetNoteId,b.id));result=[];for(const l of rows)try{const{note:n}=await permission(a,l.fromNoteId);result.push({id:n.id,title:n.title,snippet:n.bodyMd.slice(0,240)});}catch{}}
else if(name==="ask_knowledge"){const b=z.object({question:z.string().min(1).max(2000),notebook_id:z.string().uuid().optional()}).parse(x);if(b.notebook_id)await nbPermission(a,b.notebook_id,"read");result=await askKnowledge({workspaceId:a.t.workspaceId,userId:a.u.id,question:b.question,notebookId:b.notebook_id});}
else if(name==="create_note"){requireWrite(a);const b=z.object({notebook_id:z.string().uuid(),folder_id:z.string().uuid().nullable().optional(),title:z.string().min(1).max(200),content:z.string().default(""),tags:z.array(z.string().min(1).max(50)).max(50).default([])}).parse(x),{notebook:nb}=await nbPermission(a,b.notebook_id,"edit");if(b.folder_id){const[f]=await db.select().from(folders).where(and(eq(folders.id,b.folder_id),eq(folders.notebookId,nb.id),isNull(folders.trashedAt)));if(!f)throw fail("VALIDATION","目录不属于目标笔记本");}await charge(a,textBytes(b.title,b.content));await assertUserStorage(a.u.id,textBytes(b.title,b.content));const[n]=await db.insert(notes).values({workspaceId:a.t.workspaceId,notebookId:nb.id,folderId:b.folder_id??null,title:b.title,bodyMd:b.content,tags:b.tags,aiIndex:nb.defaultAiIndex,createdBy:a.u.id,updatedBy:a.u.id}).returning();await db.insert(noteVersions).values({noteId:n.id,version:1,title:n.title,bodyMd:n.bodyMd,editorId:a.u.id,source:"mcp"});// 与 UI 建note 一致：第 1 版也要留档，否则历史缺头
await writeNoteFile({...n,noteId:n.id,bodyMd:n.bodyMd});await rebuildLinks(n.id,n.workspaceId,n.bodyMd);result={id:n.id,version:n.version};}
else if(name==="update_note"||name==="append_to_note"){requireWrite(a);const b=z.object({id:z.string().uuid(),expected_version:zint().positive().optional(),content:z.string().optional(),title:z.string().min(1).max(200).optional()}).parse(x),{note:n}=await permission(a,b.id,"edit");if(name==="update_note"&&b.expected_version===undefined)throw fail("VALIDATION","expected_version 必填");if(b.expected_version!==undefined&&b.expected_version!==n.version)throw fail("CONFLICT_VERSION","版本冲突");const title=b.title??n.title,bodyMd=name==="append_to_note"?`${n.bodyMd}${n.bodyMd?"\n":""}${b.content??""}`:b.content??n.bodyMd;const delta=Math.max(0,textBytes(title,bodyMd)-textBytes(n.title,n.bodyMd));await charge(a,Buffer.byteLength(b.content??"","utf8")+Buffer.byteLength(b.title??"","utf8"));await assertUserStorage(n.createdBy,delta);// 历史行的约定：version=N 那一行存的就是「变成 N 时」的内容（见 notes.ts 的建note与保存）。
// 所以必须先更新再按新版本号落历史，早先按 n.version 落旧内容会撞 note_versions 唯一键。
const[saved]=await db.transaction(async tx=>{const rows=await tx.update(notes).set({title,bodyMd,version:n.version+1,updatedBy:a!.u.id,updatedAt:new Date()}).where(and(eq(notes.id,n.id),eq(notes.version,n.version))).returning();if(rows[0])await tx.insert(noteVersions).values({noteId:n.id,version:rows[0].version,title:rows[0].title,bodyMd:rows[0].bodyMd,editorId:a!.u.id,source:"mcp"});return rows;});if(!saved)throw fail("CONFLICT_VERSION","版本冲突");await writeNoteFile({...saved,noteId:saved.id,bodyMd:saved.bodyMd});await rebuildLinks(saved.id,saved.workspaceId,saved.bodyMd);result={id:saved.id,version:saved.version};}
else if(name==="move_note"){requireWrite(a,true);const b=z.object({id:z.string().uuid(),notebook_id:z.string().uuid(),folder_id:z.string().uuid().nullable().optional()}).parse(x),{note:n}=await permission(a,b.id,"edit"),{notebook:nb}=await nbPermission(a,b.notebook_id,"edit");if(b.folder_id){const[f]=await db.select().from(folders).where(and(eq(folders.id,b.folder_id),eq(folders.notebookId,nb.id),isNull(folders.trashedAt)));if(!f)throw fail("VALIDATION","目录不属于目标笔记本");}const[saved]=await db.update(notes).set({notebookId:nb.id,folderId:b.folder_id??null,version:n.version+1,updatedBy:a.u.id,updatedAt:new Date()}).where(eq(notes.id,n.id)).returning();await writeNoteFile({...saved,noteId:saved.id,bodyMd:saved.bodyMd});result={id:saved.id,version:saved.version};}
else if(name==="add_tags"){requireWrite(a,true);const b=z.object({id:z.string().uuid(),tags:z.array(z.string().min(1).max(50)).max(50)}).parse(x),{note:n}=await permission(a,b.id,"edit"),merged=[...new Set([...(n.tags as string[]),...b.tags])].slice(0,50);await charge(a,Buffer.byteLength(JSON.stringify(b.tags)));const[saved]=await db.update(notes).set({tags:merged,version:n.version+1,updatedBy:a.u.id,updatedAt:new Date()}).where(eq(notes.id,n.id)).returning();result={id:saved.id,version:saved.version,tags:merged};}
else if(name==="trash_note"){requireWrite(a,true);if(!a.t.allowDelete)throw fail("FORBIDDEN","钥匙未授权删除");const b=z.object({id:z.string().uuid()}).parse(x),{note:n}=await permission(a,b.id,"edit");await db.update(notes).set({trashedAt:new Date(),trashedBy:a.u.id,trashBatchId:crypto.randomUUID()}).where(eq(notes.id,n.id));result={};}else if(name==="post_to_feed"){const b=z.object({body:z.string().min(1).max(5000),scope:z.enum(["workspace","public"]).default("workspace"),note_id:z.string().uuid().optional()}).parse(x);
 if(b.scope==="public"&&!a.t.feedPublic)throw fail("FORBIDDEN","钥匙未授权发广场动态");
 if(b.scope==="workspace"&&!a.t.feedWorkspace)throw fail("FORBIDDEN","钥匙未授权发工作区动态");
 if(b.note_id)await permission(a,b.note_id,"read");
 const[ws2]=await db.select().from(workspaces).where(eq(workspaces.id,a.t.workspaceId));
 if(b.scope==="workspace"&&ws2?.frozen)throw fail("FORBIDDEN","工作区已冻结，暂时只读");
 const[post]=await db.insert(posts).values({authorUserId:a.u.id,workspaceId:b.scope==="workspace"?a.t.workspaceId:null,visibility:b.scope==="public"?"public":"workspace",body:b.body,noteId:b.note_id??null}).returning();
 result={id:post.id,scope:b.scope};}
else if(name==="list_tasks"||name==="list_events"){const kind=name==="list_tasks"?"task":"event";
 const b=z.object({from:z.string().datetime().optional(),to:z.string().datetime().optional(),status:z.enum(["open","done","all"]).default(name==="list_tasks"?"open":"all"),assignee:z.string().max(40).optional(),include_inbox:zbool().default(true),limit:zint().min(1).max(200).default(200)}).parse(x);
 // 默认窗口「今天起 14 天」（架构 03 §5）：从当地日历日 00:00 起，否则今天早些时候到期的会被切掉
 const from=b.from?new Date(b.from):startOfLocalDay(new Date(),DEFAULT_TZ),to=b.to?new Date(b.to):new Date(from.getTime()+14*86400000);
 if(to<=from)throw fail("VALIDATION","结束时间必须晚于开始时间");
 if(to.getTime()-from.getTime()>400*86400000)throw fail("VALIDATION","一次最多查 400 天");
 let rows=(await db.select().from(calendarItems).where(and(eq(calendarItems.workspaceId,a.t.workspaceId),eq(calendarItems.kind,kind),isNull(calendarItems.trashedAt))));
 if(b.assignee&&b.assignee!=="any"){const handle=b.assignee==="me"?a.u.handle:b.assignee.replace(/^[+@]+/,"");const[who]=await db.select().from(users).where(eq(users.handle,handle));rows=rows.filter(r=>!!who&&r.assigneeUserId===who.id);}
 const visible=await visibleCalendarItems(a,rows);
 const ovs=visible.length?await db.select().from(calendarOverrides).where(inArray(calendarOverrides.itemId,visible.map(r=>r.id))):[];
 const byItem=new Map<string,Array<typeof calendarOverrides.$inferSelect>>();for(const o of ovs)byItem.set(o.itemId,[...(byItem.get(o.itemId)??[]),o]);
 const noteIds=[...new Set(visible.map(r=>r.sourceNoteId).filter((v):v is string=>!!v))];
 const titles=new Map((noteIds.length?await db.select({id:notes.id,title:notes.title}).from(notes).where(inArray(notes.id,noteIds)):[]).map(n=>[n.id,n.title]));
 const dto=(r:typeof calendarItems.$inferSelect,at:Date|null,occ:Date|null,status:string)=>({id:r.id,title:r.title,kind:r.kind,status,priority:r.priority,all_day:r.allDay,[kind==="task"?"due_at":"starts_at"]:at,ends_at:r.endsAt,occurrence_start:occ,timezone:r.timezone,recurring:!!r.rrule,rrule:r.rrule,source:r.source,link_state:r.linkState,source_note_id:r.sourceNoteId,note_title:r.sourceNoteId?titles.get(r.sourceNoteId)??null:null,url:`${env.publicUrl}/w/${a!.t.workspaceId}/calendar?item=${r.id}`});
 const out=visible.filter(r=>r.startsAt??r.dueAt).flatMap(r=>occurrencesOf(r,byItem.get(r.id)??[],from,to).map(o=>dto(r,o.start,o.occurrenceStart,o.status)));
 // 收件箱（无期限的待办）默认一起给：问「我要做什么」的人不会希望漏掉没排期的那些
 if(kind==="task"&&b.include_inbox)out.push(...visible.filter(r=>!r.startsAt&&!r.dueAt).map(r=>dto(r,null,null,r.status)));
 result={items:out.filter(r=>b.status==="all"||r.status===b.status).sort((p,q)=>Number(p.occurrence_start??0)-Number(q.occurrence_start??0)).slice(0,b.limit)};}
else if(name==="create_task"){requireWrite(a);
 // 刻意只让建独立任务：否则一把「只读笔记」的钥匙能靠建任务绕道改正文（设计 16 §6.3）
 const b=z.object({title:z.string().min(1).max(200),due_at:z.string().datetime().nullish(),all_day:zbool().default(false),priority:zint().min(0).max(3).default(0),note:z.string().max(2000).default("")}).parse(x);
 const[ws3]=await db.select().from(workspaces).where(eq(workspaces.id,a.t.workspaceId));
 if(ws3?.frozen)throw fail("FORBIDDEN","工作区已冻结，暂时只读");
 const[total]=await db.select({n:count()}).from(calendarItems).where(eq(calendarItems.workspaceId,a.t.workspaceId));
 if((total?.n??0)>=50000)throw fail("QUOTA","日历项已达上限，请先清理");
 await charge(a,textBytes(b.title,b.note));
 const due=b.due_at?new Date(b.due_at):null;
 const[row]=await db.insert(calendarItems).values({workspaceId:a.t.workspaceId,kind:"task",title:b.title.trim(),bodyMd:b.note,allDay:b.all_day,dueAt:due,timezone:DEFAULT_TZ,priority:b.priority,source:"mcp",createdBy:a.u.id,updatedBy:a.u.id}).returning();
 result={id:row.id,title:row.title,due_at:row.dueAt,status:row.status,url:`${env.publicUrl}/w/${a.t.workspaceId}/calendar?item=${row.id}`};}
else if(name==="complete_task"){requireWrite(a);
 const b=z.object({id:z.string().uuid(),done:zbool().default(true),occurrence_start:z.string().datetime().optional()}).parse(x);
 const[item]=await db.select().from(calendarItems).where(eq(calendarItems.id,b.id));
 if(!item||item.trashedAt||item.workspaceId!==a.t.workspaceId)throw fail("NOT_FOUND","日历项不存在");
 if(!(await visibleCalendarItems(a,[item])).length)throw fail("NOT_FOUND","日历项不存在");
 // 回写正文等于改笔记，所以要按「能编辑这篇笔记」判，而不是只看条目可见
 if(item.source==="note"&&item.sourceNoteId)await permission(a,item.sourceNoteId,"edit");
 const[ws4]=await db.select().from(workspaces).where(eq(workspaces.id,item.workspaceId));
 if(ws4?.frozen)throw fail("FORBIDDEN","工作区已冻结，暂时只读");
 await charge(a,textBytes(item.title,""));
 const r=await completeCalendarItem(item,a.u.id,b.done,b.occurrence_start?new Date(b.occurrence_start):undefined,"mcp");
 result={id:item.id,status:r.status,note_written:r.noteWritten,detached:r.detached,note_id:r.noteId};}
else throw fail("VALIDATION","未知工具");await db.insert(auditLogs).values({userId:a.u.id,workspaceId:a.t.workspaceId,actorType:"mcp",actorId:a.t.id,action:`mcp.${name}`,result:"ok",details:{arguments:auditArgs(x)}}).catch(e=>console.warn("mcp 审计写入失败（不影响本次调用）:",e));const sc=result&&typeof result==="object"&&!Array.isArray(result)?result:undefined;return c.json({jsonrpc:"2.0",id,result:{content:[{type:"text",text:JSON.stringify(result)}],...(sc?{structuredContent:sc}:{})}});
}catch(e){
  // 未认证必须回 401 且带 WWW-Authenticate，云端客户端靠它发现授权服务器（RFC 9728）
  if(e instanceof AppError&&e.code==="UNAUTHENTICATED")return unauthorized(c,id,e.message);
  if(a)await db.insert(auditLogs).values({userId:a.u.id,workspaceId:a.t.workspaceId,actorType:"mcp",actorId:a.t.id,action:`mcp.${name||"request"}`,result:"error",details:{message:e instanceof Error?e.message:String(e)}}).catch(err=>console.warn("mcp 审计写入失败（不影响本次调用）:",err));return c.json({jsonrpc:"2.0",id,error:{code:-32000,message:e instanceof Error?e.message:String(e)}});}});
