import { Hono } from "hono";
import { and,count,desc,eq,inArray,isNull,sql } from "drizzle-orm";
import { z } from "zod";
import { AppError, fail } from "@kb/shared";
import { db } from "../db/client.ts";
import { env } from "../env.ts";
import { attachments,auditLogs,calendarItems,calendarOverrides,folders,links,mcpTokens,notebookMembers,notebooks,notes,noteVersions,posts,users,workspaceMembers,workspaces } from "../db/schema.ts";
import { ok } from "../http.ts";import { currentUser } from "../lib/session.ts";import { hashSecret,secretHashes,secureToken } from "../lib/tokens.ts";import { memberRole } from "../lib/workspace.ts";import { writeNoteFile } from "../lib/files.ts";import { rebuildLinks } from "../lib/links.ts";import { relocateNote } from "../lib/note-move.ts";import { assertUserStorage,textBytes } from "../lib/quota.ts";import { limit } from "../lib/rate-limit.ts";import { noteAccess } from "../lib/note-access.ts";import { askKnowledgeAcross } from "../lib/knowledge-ai.ts";import { notebookAccess } from "../lib/notebook-access.ts";import { instanceConfig,moderationOn,queueReview } from "../lib/moderation.ts";import { completeCalendarItem,DEFAULT_TZ,occurrencesOf,startOfLocalDay,wallParts } from "../lib/calendar.ts";
import { assertTokenWorkspaces, liveWorkspaceIds, resolveWorkspaceIds, tokenDto } from "../lib/mcp-workspaces.ts";
import { MCP_INSTRUCTIONS, TOOL_DEFS, isWriteTool, toolAllowed, toolsFor } from "../lib/mcp-protocol.ts";
import { abortIdempotent, finishIdempotent, readIdempotencyKey, startIdempotent, type IdempotencyClaim } from "../lib/mcp-idempotency.ts";
import { buildNotePaths, listRecentNotes, searchNotesInScope } from "../lib/mcp-query.ts";
import { NOTE_SLICE_DEFAULT, sliceNoteBody } from "../lib/note-slice.ts";
import { cursorAfter, finishCursorPage, pageByCursor } from "../lib/mcp-pagination.ts";
import { attachmentMarkdown, decodeImageData, MCP_IMAGE_MIME, mcpImageMaxBytes, saveNoteAttachment } from "../lib/attachments.ts";
import { assertAttachmentType } from "../lib/file-type.ts";
export const mcpRoutes=new Hono();
type Ctx=Parameters<typeof currentUser>[0];
async function user(c:Ctx){const u=await currentUser(c);if(!u)throw fail("UNAUTHENTICATED","未登录");return u;}
function mcpConfigs(_c:Ctx,secret:string){const url=`${env.publicUrl}/api/v1/mcp`;return{config:{mcpServers:{knowledge:{url,headers:{Authorization:`Bearer ${secret}`}}}},stdioConfig:{mcpServers:{knowledge:{command:"npx",args:["-y","mcp-remote",url,"--header",`Authorization: Bearer ${secret}`]}}}};}
mcpRoutes.get("/mcp/tokens",async c=>{const u=await user(c);const rows=await db.select().from(mcpTokens).where(eq(mcpTokens.userId,u.id));const list=c.req.query("includeRevoked")==="1"?rows:rows.filter(t=>t.status==="active");return ok(c,{tokens:list.map(tokenDto)});});
mcpRoutes.post("/mcp/tokens",async c=>{const u=await user(c);const b=z.object({name:z.string().min(1).max(80),workspaceId:z.string().uuid().optional(),workspaceIds:z.array(z.string().uuid()).min(1).max(50).optional(),notebookMode:z.enum(["inherit","allowlist"]).default("inherit"),notebookIds:z.array(z.string().uuid()).default([]),rw:z.enum(["read","write","manage"]),allowDelete:z.boolean().default(false),requireAiIndex:z.boolean().default(true),allowPrivateNotebooks:z.boolean().default(false),feedPublic:z.boolean().default(false),feedWorkspace:z.boolean().default(false),dailyWriteLimitBytes:z.number().int().min(1024).max(1073741824).nullable().default(null),expiresInDays:z.number().int().min(1).max(365).nullable().optional()}).parse(await c.req.json());const workspaceIds=resolveWorkspaceIds(b);await assertTokenWorkspaces(u.id,workspaceIds,b.rw);if(b.allowDelete&&b.rw!=="manage")throw fail("VALIDATION","只有管理钥匙可允许删除");for(const id of b.notebookIds){const x=await notebookAccess(id,u.id,b.rw==="read"?"read":"edit");if(!workspaceIds.includes(x.workspace.id))throw fail("VALIDATION","指定的笔记本不属于勾选的工作区");}const id=crypto.randomUUID(),secret=`kbk_${id.slice(0,8)}_${secureToken(24)}`;await db.insert(mcpTokens).values({id,secretHash:hashSecret(secret),name:b.name,userId:u.id,workspaceId:workspaceIds[0]!,workspaceIds,notebookMode:b.notebookMode,notebookIds:b.notebookIds,rw:b.rw,allowDelete:b.allowDelete,requireAiIndex:b.requireAiIndex,allowPrivateNotebooks:b.allowPrivateNotebooks,feedPublic:b.feedPublic,feedWorkspace:b.feedWorkspace,dailyWriteLimitBytes:b.dailyWriteLimitBytes,expiresAt:b.expiresInDays?new Date(Date.now()+b.expiresInDays*86400000):null});return ok(c,{id,secret,...mcpConfigs(c,secret)},201);});
mcpRoutes.post("/mcp/tokens/:id/rotate",async c=>{const u=await user(c);const[old]=await db.select().from(mcpTokens).where(and(eq(mcpTokens.id,c.req.param("id")),eq(mcpTokens.userId,u.id)));if(!old||old.status!=="active")throw fail("NOT_FOUND","钥匙不存在");const id=crypto.randomUUID(),secret=`kbk_${id.slice(0,8)}_${secureToken(24)}`;await db.transaction(async tx=>{await tx.update(mcpTokens).set({status:"revoked"}).where(eq(mcpTokens.id,old.id));await tx.insert(mcpTokens).values({...old,id,secretHash:hashSecret(secret),status:"active",lastUsedAt:null,createdAt:new Date()});});return ok(c,{id,secret,...mcpConfigs(c,secret)},201);});
mcpRoutes.patch("/mcp/tokens/:id",async c=>{const u=await user(c);const[t]=await db.select().from(mcpTokens).where(and(eq(mcpTokens.id,c.req.param("id")),eq(mcpTokens.userId,u.id)));if(!t||t.status!=="active")throw fail("NOT_FOUND","钥匙不存在");const b=z.object({name:z.string().min(1).max(80).optional(),workspaceId:z.string().uuid().optional(),workspaceIds:z.array(z.string().uuid()).min(1).max(50).optional(),notebookMode:z.enum(["inherit","allowlist"]).optional(),notebookIds:z.array(z.string().uuid()).optional(),rw:z.enum(["read","write","manage"]).optional(),allowDelete:z.boolean().optional(),requireAiIndex:z.boolean().optional(),allowPrivateNotebooks:z.boolean().optional(),feedPublic:z.boolean().optional(),feedWorkspace:z.boolean().optional(),dailyWriteLimitBytes:z.number().int().min(1024).max(1073741824).nullable().optional(),expiresInDays:z.number().int().min(1).max(365).nullable().optional()}).parse(await c.req.json());const rw=b.rw??t.rw,allowDelete=b.allowDelete??t.allowDelete,mode=b.notebookMode??t.notebookMode,notebookIds=b.notebookIds??(t.notebookIds as string[]);const workspaceIds=b.workspaceIds||b.workspaceId?resolveWorkspaceIds(b):await liveWorkspaceIds(t,u.id);if(!workspaceIds.length)throw fail("FORBIDDEN","不是工作区成员");await assertTokenWorkspaces(u.id,workspaceIds,rw);if(allowDelete&&rw!=="manage")throw fail("VALIDATION","只有管理钥匙可允许删除");if(mode==="allowlist")for(const id of notebookIds){const x=await notebookAccess(id,u.id,rw==="read"?"read":"edit");if(!workspaceIds.includes(x.workspace.id))throw fail("VALIDATION","指定的笔记本不属于勾选的工作区");}await db.update(mcpTokens).set({workspaceId:workspaceIds[0]!,workspaceIds,...(b.name!==undefined?{name:b.name}:{}),notebookMode:mode,notebookIds,rw,allowDelete,...(b.requireAiIndex!==undefined?{requireAiIndex:b.requireAiIndex}:{}),...(b.allowPrivateNotebooks!==undefined?{allowPrivateNotebooks:b.allowPrivateNotebooks}:{}),...(b.feedPublic!==undefined?{feedPublic:b.feedPublic}:{}),...(b.feedWorkspace!==undefined?{feedWorkspace:b.feedWorkspace}:{}),...(b.dailyWriteLimitBytes!==undefined?{dailyWriteLimitBytes:b.dailyWriteLimitBytes}:{}),...(b.expiresInDays!==undefined?{expiresAt:b.expiresInDays?new Date(Date.now()+b.expiresInDays*86400000):null}:{})}).where(eq(mcpTokens.id,t.id));return ok(c,{});});
mcpRoutes.delete("/mcp/tokens/:id",async c=>{const u=await user(c);await db.update(mcpTokens).set({status:"revoked"}).where(and(eq(mcpTokens.id,c.req.param("id")),eq(mcpTokens.userId,u.id)));return ok(c,{});});
mcpRoutes.get("/workspaces/:id/mcp-audit",async c=>{
  const u=await user(c),wsId=c.req.param("id"),role=await memberRole(wsId,u.id);
  if(!role)throw fail("FORBIDDEN","不是工作区成员");
  const q=z.object({tokenId:z.string().uuid().optional(),tool:z.string().max(80).optional(),result:z.enum(["ok","error"]).optional(),limit:z.coerce.number().int().min(1).max(200).default(50)}).parse(c.req.query());
  const conds=[eq(auditLogs.workspaceId,wsId),eq(auditLogs.actorType,"mcp")];
  if(role!=="owner"&&role!=="admin")conds.push(eq(auditLogs.userId,u.id));
  if(q.tokenId)conds.push(eq(auditLogs.actorId,q.tokenId));
  if(q.result)conds.push(eq(auditLogs.result,q.result));
  if(q.tool)conds.push(eq(auditLogs.action,q.tool.startsWith("mcp.")?q.tool:`mcp.${q.tool}`));
  const rows=await db.select({id:auditLogs.id,tokenId:auditLogs.actorId,tokenName:mcpTokens.name,userId:auditLogs.userId,action:auditLogs.action,result:auditLogs.result,details:auditLogs.details,createdAt:auditLogs.createdAt}).from(auditLogs).leftJoin(mcpTokens,eq(mcpTokens.id,auditLogs.actorId)).where(and(...conds)).orderBy(desc(auditLogs.createdAt)).limit(q.limit);
  return ok(c,{logs:rows});
});
type Auth={t:typeof mcpTokens.$inferSelect;u:typeof users.$inferSelect;workspaceIds:string[]};
function covers(a:Auth,wsId:string){return a.workspaceIds.includes(wsId);}
function pickWorkspace(a:Auth,requested?:string|null){if(requested){if(!covers(a,requested))throw fail("FORBIDDEN","工作区不在钥匙范围");return requested;}if(a.workspaceIds.length===1)return a.workspaceIds[0]!;throw fail("VALIDATION","这把钥匙绑定了多个工作区，请传入 workspace_id");}
function scopeIds(a:Auth,requested?:string|null){return requested?[pickWorkspace(a,requested)]:a.workspaceIds;}
async function auth(c:Ctx):Promise<Auth>{const bearer=c.req.header("Authorization")?.match(/^Bearer (.+)$/)?.[1];if(!bearer)throw fail("UNAUTHENTICATED","缺少 Bearer token");const[t]=await db.select().from(mcpTokens).where(inArray(mcpTokens.secretHash,secretHashes(bearer)));if(!t||t.status!=="active"||(t.expiresAt&&t.expiresAt<=new Date()))throw fail("UNAUTHENTICATED","MCP 钥匙无效");const[u]=await db.select().from(users).where(eq(users.id,t.userId));const workspaceIds=u?await liveWorkspaceIds(t,u.id):[];if(!u||u.status!=="active"||!workspaceIds.length)throw fail("FORBIDDEN","用户或成员资格不可用");limit(`mcp:${t.id}`,60,60000);if(!t.lastUsedAt||Date.now()-t.lastUsedAt.getTime()>30_000)await db.update(mcpTokens).set({lastUsedAt:new Date()}).where(eq(mcpTokens.id,t.id));return{t,u,workspaceIds};}
function inScope(a:Auth,notebookId:string){return a.t.notebookMode!=="allowlist"||(a.t.notebookIds as string[]).includes(notebookId);}
function hideRead(mode:"read"|"edit",code:"FORBIDDEN"|"NOT_FOUND",msg:string){return fail(mode==="read"?"NOT_FOUND":code,mode==="read"?"笔记不存在":msg);}
async function nbPermission(a:Auth,id:string,mode:"read"|"edit"){if(!inScope(a,id))throw fail(mode==="read"?"NOT_FOUND":"FORBIDDEN",mode==="read"?"笔记本不存在":"笔记本不在钥匙范围");const x=await notebookAccess(id,a.u.id,mode);if(!covers(a,x.workspace.id))throw fail(mode==="read"?"NOT_FOUND":"FORBIDDEN",mode==="read"?"笔记本不存在":"跨工作区访问");if(x.notebook.visibility==="private"&&!a.t.allowPrivateNotebooks)throw fail(mode==="read"?"NOT_FOUND":"FORBIDDEN",mode==="read"?"笔记本不存在":"钥匙不允许私密笔记本");return x;}
async function permission(a:Auth,id:string,mode:"read"|"edit"="read"){const x=await noteAccess(id,a.u.id,mode);if(!covers(a,x.workspace.id)||!inScope(a,x.notebook.id))throw hideRead(mode,"FORBIDDEN","笔记不在钥匙范围");if(x.notebook.visibility==="private"&&!a.t.allowPrivateNotebooks)throw hideRead(mode,"FORBIDDEN","钥匙不允许私密笔记本");if(mode==="read"&&a.t.requireAiIndex&&!x.note.aiIndex)throw fail("NOT_FOUND","笔记不存在");return x;}
async function acceptNote(a:Auth,id:string){try{await permission(a,id,"read");return true;}catch{return false;}}
async function scopedNotebooks(a:Auth){const rows=await db.select().from(notebooks).where(and(inArray(notebooks.workspaceId,a.workspaceIds),isNull(notebooks.trashedAt)));const out:Array<{id:string;title:string;slug:string;visibility:string;workspace_id:string}>=[];for(const nb of rows)try{await nbPermission(a,nb.id,"read");out.push({id:nb.id,title:nb.title,slug:nb.slug,visibility:nb.visibility,workspace_id:nb.workspaceId});}catch{}return out;}
async function cursorContext(a:Auth,tool:string,filters:unknown){const wsRoles=await db.select({workspaceId:workspaceMembers.workspaceId,role:workspaceMembers.role}).from(workspaceMembers).where(and(eq(workspaceMembers.userId,a.u.id),inArray(workspaceMembers.workspaceId,a.workspaceIds))),nbRoles=await db.select({notebookId:notebookMembers.notebookId,role:notebookMembers.role}).from(notebookMembers).innerJoin(notebooks,eq(notebooks.id,notebookMembers.notebookId)).where(and(eq(notebookMembers.userId,a.u.id),inArray(notebooks.workspaceId,a.workspaceIds)));return{tool,filters,secret:env.appSecret,scope:{token_id:a.t.id,workspace_ids:[...a.workspaceIds].sort(),workspace_roles:wsRoles.sort((x,y)=>x.workspaceId.localeCompare(y.workspaceId)),notebook_roles:nbRoles.sort((x,y)=>x.notebookId.localeCompare(y.notebookId)),rw:a.t.rw,notebook_mode:a.t.notebookMode,notebook_ids:[...(a.t.notebookIds as string[])].sort(),require_ai_index:a.t.requireAiIndex,allow_private_notebooks:a.t.allowPrivateNotebooks}};}
function requireWrite(a:Auth,manage=false){if(a.t.rw==="read"||(manage&&a.t.rw!=="manage"))throw fail("FORBIDDEN",manage?"需要 manage 权限":"钥匙只读");}async function charge(a:Auth,bytes:number){const day=new Date().toISOString().slice(0,10),cap=a.t.dailyWriteLimitBytes;const rows=await db.execute(cap==null?sql`INSERT INTO mcp_daily_usage(token_id,day,write_bytes) VALUES(${a.t.id},${day},${bytes}) ON CONFLICT(token_id,day) DO UPDATE SET write_bytes=mcp_daily_usage.write_bytes+${bytes} RETURNING write_bytes`:sql`INSERT INTO mcp_daily_usage(token_id,day,write_bytes) VALUES(${a.t.id},${day},${bytes}) ON CONFLICT(token_id,day) DO UPDATE SET write_bytes=mcp_daily_usage.write_bytes+${bytes} WHERE mcp_daily_usage.write_bytes+${bytes}<=${cap} RETURNING write_bytes`);if(!rows.length)throw fail("QUOTA","已达到 MCP 每日写入字节额度");}
/** 日历条目的可见性：来自笔记的完全继承笔记（连钥匙的笔记本范围、ai_index、私密开关一起继承），其余按 visibility。 */
async function visibleCalendarItems(a:Auth,rows:Array<typeof calendarItems.$inferSelect>){const out:Array<typeof calendarItems.$inferSelect>=[];for(const r of rows){if(r.source==="note"&&r.sourceNoteId){try{await permission(a,r.sourceNoteId);}catch{continue;}}else if(r.visibility==="private"&&r.createdBy!==a.u.id)continue;out.push(r);}return out;}
/** 客户端若没拿到 inputSchema（比如缓存着旧的空 schema），数字与布尔会以字符串发过来。
 *  工具层统一容忍这一种松散写法，别让调用方在类型上翻车。 */
const zint=()=>z.coerce.number().int();
const zbool=()=>z.union([z.boolean(),z.enum(["true","false"]).transform(v=>v==="true")]);
async function commitNote(a:Auth,n:typeof notes.$inferSelect,title:string,bodyMd:string,opts?:{chargeBytes?:number;alreadyCharged?:boolean}){
  if(!opts?.alreadyCharged)await charge(a,opts?.chargeBytes??Math.max(0,textBytes(title,bodyMd)-textBytes(n.title,n.bodyMd)));
  const delta=Math.max(0,textBytes(title,bodyMd)-textBytes(n.title,n.bodyMd));
  await assertUserStorage(n.createdBy,delta);
  const[saved]=await db.transaction(async tx=>{
    const rows=await tx.update(notes).set({title,bodyMd,version:n.version+1,updatedBy:a.u.id,updatedAt:new Date()}).where(and(eq(notes.id,n.id),eq(notes.version,n.version))).returning();
    if(rows[0])await tx.insert(noteVersions).values({noteId:n.id,version:rows[0].version,title:rows[0].title,bodyMd:rows[0].bodyMd,editorId:a.u.id,source:"mcp"});
    return rows;
  });
  if(!saved)throw fail("CONFLICT_VERSION","版本冲突",{version:String(n.version)});
  await writeNoteFile({...saved,noteId:saved.id,bodyMd:saved.bodyMd});
  await rebuildLinks(saved.id,saved.workspaceId,saved.bodyMd);
  return{id:saved.id,version:saved.version};
}
function countOcc(hay:string,needle:string){if(!needle)return 0;let n=0,i=0;while((i=hay.indexOf(needle,i))>=0){n++;i+=needle.length;}return n;}
/** 未认证的应答：401 且带 WWW-Authenticate，云端客户端靠它发现授权服务器（RFC 9728）。 */
function unauthorized(c:Ctx,id:unknown,message:string){return c.json({jsonrpc:"2.0",id,error:{code:-32001,message}},401,{"WWW-Authenticate":`Bearer resource_metadata="${env.publicUrl}/.well-known/oauth-protected-resource"`});}
/** Streamable HTTP 的客户端会先 GET 一次，探服务端主动推的那条 SSE 流；会话结束时可能发 DELETE。
 *  这个端点是纯请求-响应，按协议回 405 客户端就认了。以前这两个动词落到 404 上，有的客户端
 *  会把它理解成「端点不存在」而不是「这里没有 SSE」，于是不停重连——看着就像服务不稳定。
 *  没带 token 的探测仍旧回 401，别把发现授权服务器那条路一起堵死。 */
mcpRoutes.on(["GET","DELETE"],"/mcp",c=>c.req.header("Authorization")?c.json({jsonrpc:"2.0",id:null,error:{code:-32000,message:"该端点只接受 POST"}},405,{Allow:"POST"}):unauthorized(c,null,"缺少 Bearer token"));
/** 审计只记「调了什么」，不记正文：一篇笔记已经在 notes 和 note_versions 里各存了一份，
 *  再往 audit_logs 的 jsonb 里塞第三份，批量迁移时库会被撑大好几倍，大 jsonb 的插入
 *  本身也会把这次写请求拖慢。长字符串一律截断，id / 标题这些短字段原样留着。 */
function auditArgs(x:unknown){if(!x||typeof x!=="object"||Array.isArray(x))return x;const out:Record<string,unknown>={};for(const[k,v]of Object.entries(x as Record<string,unknown>))out[k]=typeof v==="string"&&v.length>200?`${v.slice(0,200)}…（共 ${v.length} 字，正文见笔记本身）`:v;return out;}
mcpRoutes.post("/mcp",async c=>{let a:Auth|undefined,name="",id:unknown=null,idemClaim:IdempotencyClaim|undefined;try{a=await auth(c);const body=z.object({jsonrpc:z.literal("2.0"),id:z.any().optional(),method:z.string(),params:z.any().optional()}).parse(await c.req.json());id=body.id??null;if(body.method==="initialize")return c.json({jsonrpc:"2.0",id,result:{protocolVersion:"2025-03-26",capabilities:{tools:{listChanged:false}},serverInfo:{name:"knowledge-brain",version:"1.1.0"},instructions:MCP_INSTRUCTIONS}});if(body.method.startsWith("notifications/"))return c.body(null,204);if(body.method==="ping")return c.json({jsonrpc:"2.0",id,result:{}});if(body.method==="tools/list")return c.json({jsonrpc:"2.0",id,result:{tools:toolsFor(a.t)}});if(body.method!=="tools/call"){name=body.method;throw fail("VALIDATION",`不支持的方法：${body.method}`);}name=String(body.params?.name??"");const x=body.params?.arguments??{};if(!TOOL_DEFS[name])throw fail("VALIDATION","未知工具");if(!toolAllowed(a.t,name))throw fail("FORBIDDEN","钥匙没有这个工具");
/** MCP 工具的返回值按协议就是任意 JSON：要么是一组条目，要么是一个对象。 */
type ToolResult=Array<Record<string,unknown>>|Record<string,unknown>|undefined;let result:ToolResult;
 const dryRun=!!(x&&typeof x==="object"&&!Array.isArray(x)&&((x as Record<string,unknown>).dry_run===true||(x as Record<string,unknown>).dry_run==="true"));
 const idem=isWriteTool(name)&&!dryRun?readIdempotencyKey(c.req.header("Idempotency-Key"),x):undefined;
 if(idem){const started=await startIdempotent(a.t.id,name,idem,x);if(started.kind==="replay")result=started.result as ToolResult;else idemClaim=started.claim;}
if(result===undefined&&name==="get_me"){const spaces=await db.select({id:workspaces.id,name:workspaces.name}).from(workspaces).where(inArray(workspaces.id,a.workspaceIds));const ordered=a.workspaceIds.map(id=>spaces.find(s=>s.id===id)).filter((s):s is {id:string;name:string}=>!!s);result={handle:a.u.handle,workspace:ordered[0]??null,workspaces:ordered,rw:a.t.rw,notebook_mode:a.t.notebookMode,notebooks:await scopedNotebooks(a),expires_at:a.t.expiresAt,require_ai_index:a.t.requireAiIndex,allow_private_notebooks:a.t.allowPrivateNotebooks,allow_delete:a.t.allowDelete,image_max_bytes:await mcpImageMaxBytes()};}
else if(result===undefined&&name==="list_notebooks"){const b=z.object({limit:zint().min(1).max(200).default(50),cursor:z.string().optional()}).parse(x),items=await scopedNotebooks(a),ctx=await cursorContext(a,name,{}),page=pageByCursor({...ctx,cursor:b.cursor,limit:b.limit,items,keyOf:n=>[n.title,n.id],directions:["asc","asc"]});result={...page,notebooks:page.items};}
else if(result===undefined&&name==="list_folder"){const b=z.object({notebook_id:z.string().uuid(),folder_id:z.string().uuid().nullable().optional(),limit:zint().min(1).max(200).default(50),cursor:z.string().optional()}).parse(x);await nbPermission(a,b.notebook_id,"read");const fs=await db.select().from(folders).where(and(eq(folders.notebookId,b.notebook_id),isNull(folders.trashedAt)));const ns=await db.select().from(notes).where(and(eq(notes.notebookId,b.notebook_id),isNull(notes.trashedAt)));const items=[...fs.filter(f=>(f.parentId??null)===(b.folder_id??null)).map(f=>({type:"folder" as const,id:f.id,title:f.title})),...ns.filter(n=>(n.folderId??null)===(b.folder_id??null)&&(!a!.t.requireAiIndex||n.aiIndex)).map(n=>({type:"note" as const,id:n.id,title:n.title}))],ctx=await cursorContext(a,name,{notebook_id:b.notebook_id,folder_id:b.folder_id??null}),page=pageByCursor({...ctx,cursor:b.cursor,limit:b.limit,items,keyOf:item=>[item.type==="folder"?0:1,item.title,item.id],directions:["asc","asc","asc"]});result={...page,folders:page.items.filter(item=>item.type==="folder").map(({id,title})=>({id,title})),notes:page.items.filter(item=>item.type==="note").map(({id,title})=>({id,title}))};}
else if(result===undefined&&name==="search_notes"){const b=z.object({query:z.string().min(1).max(200),notebook_id:z.string().uuid().optional(),workspace_id:z.string().uuid().optional(),tag:z.string().optional(),mode:z.enum(["keyword","semantic","hybrid"]).default("hybrid"),limit:zint().min(1).max(20).default(8)}).parse(x);if(b.notebook_id)await nbPermission(a,b.notebook_id,"read");result={hits:await searchNotesInScope({workspaceIds:scopeIds(a,b.workspace_id),userId:a.u.id,query:b.query,notebookId:b.notebook_id,tag:b.tag,mode:b.mode,limit:b.limit,accept:id=>acceptNote(a!,id)})};}
else if(result===undefined&&name==="get_note"){const b=z.object({id:z.string().uuid(),offset:z.number().int().min(0).optional(),max_chars:z.number().int().min(200).max(20000).optional()}).parse(x),{note:n}=await permission(a,b.id);const ls=await db.select().from(links).where(eq(links.fromNoteId,n.id));const paths=await buildNotePaths(a.workspaceIds,[{id:n.id,notebookId:n.notebookId,folderId:n.folderId,title:n.title}]);const slice=sliceNoteBody(n.bodyMd,b.offset??0,b.max_chars??NOTE_SLICE_DEFAULT);result={id:n.id,title:n.title,path:paths.get(n.id)??[n.title],body_md:slice.body_md,version:n.version,tags:n.tags,ai_index:n.aiIndex,published:n.published,links:ls.map(l=>({raw:l.raw,target_id:l.targetNoteId,state:l.state})),offset:slice.offset,total_chars:slice.total_chars,truncated:slice.truncated};}
else if(result===undefined&&name==="get_backlinks"){const b=z.object({id:z.string().uuid()}).parse(x);await permission(a,b.id);const rows=await db.select().from(links).where(eq(links.targetNoteId,b.id));const items:Array<Record<string,unknown>>=[];for(const l of rows)try{const{note:n}=await permission(a,l.fromNoteId);items.push({id:n.id,title:n.title,snippet:n.bodyMd.slice(0,240)});}catch{}result={items};}
else if(result===undefined&&name==="ask_knowledge"){const b=z.object({question:z.string().min(1).max(2000),notebook_id:z.string().uuid().optional(),workspace_id:z.string().uuid().optional()}).parse(x);if(b.notebook_id)await nbPermission(a,b.notebook_id,"read");result=await askKnowledgeAcross({workspaceIds:scopeIds(a,b.workspace_id),userId:a.u.id,question:b.question,notebookId:b.notebook_id,filterNoteId:id=>acceptNote(a!,id)});}
else if(result===undefined&&name==="list_recent"){const b=z.object({since:z.string().datetime().optional(),workspace_id:z.string().uuid().optional(),limit:zint().min(1).max(50).default(20),cursor:z.string().optional()}).parse(x),workspaceIds=scopeIds(a,b.workspace_id),ctx=await cursorContext(a,name,{since:b.since??null,workspace_id:b.workspace_id??null}),key=cursorAfter(b.cursor,ctx);if(key&&(key.length!==2||typeof key[0]!=="string"||typeof key[1]!=="string"||!Number.isFinite(new Date(key[0]).getTime())))throw fail("INVALID_CURSOR","cursor 排序键不合法");const recent=await listRecentNotes({workspaceIds,since:b.since?new Date(b.since):undefined,limit:b.limit+1,after:key?{updatedAt:new Date(key[0] as string),id:key[1] as string}:undefined,accept:id=>acceptNote(a!,id)}),page=finishCursorPage({...ctx,limit:b.limit,items:recent,keyOf:n=>[n.updated_at.toISOString(),n.id]});result={...page,notes:page.items};}
else if(result===undefined&&name==="list_attachments"){const b=z.object({note_id:z.string().uuid()}).parse(x);await permission(a,b.note_id);const rows=await db.select().from(attachments).where(and(eq(attachments.noteId,b.note_id),isNull(attachments.trashedAt)));result={attachments:rows.map(r=>({id:r.id,filename:r.filename,mime:r.mime,bytes:r.bytes,markdown:attachmentMarkdown(r.filename,r.id,r.mime)}))};}
else if(result===undefined&&name==="upload_image"){requireWrite(a);const b=z.object({note_id:z.string().uuid(),filename:z.string().min(1).max(180),mime:z.enum(MCP_IMAGE_MIME),data_base64:z.string().min(1),client_request_id:z.string().uuid().optional()}).parse(x);const{note:n}=await permission(a,b.note_id,"edit");const bytes=decodeImageData(b.data_base64);const cap=await mcpImageMaxBytes();if(bytes.length>cap)throw fail("QUOTA",`图片不能超过 ${Math.round(cap/1048576)} MB`);assertAttachmentType(b.mime,bytes);await charge(a,bytes.length);const saved=await saveNoteAttachment({note:n,userId:a.u.id,filename:b.filename,declaredMime:b.mime,bytes,maxBytes:cap});result={id:saved.id,filename:saved.filename,mime:saved.mime,bytes:saved.bytes,markdown:saved.markdown};}
else if(result===undefined&&name==="create_note"){requireWrite(a);const b=z.object({notebook_id:z.string().uuid(),folder_id:z.string().uuid().nullable().optional(),title:z.string().min(1).max(200),content:z.string().default(""),tags:z.array(z.string().min(1).max(50)).max(50).default([]),client_request_id:z.string().uuid().optional()}).parse(x),{notebook:nb}=await nbPermission(a,b.notebook_id,"edit");if(b.folder_id){const[f]=await db.select().from(folders).where(and(eq(folders.id,b.folder_id),eq(folders.notebookId,nb.id),isNull(folders.trashedAt)));if(!f)throw fail("VALIDATION","目录不属于目标笔记本");}await charge(a,textBytes(b.title,b.content));await assertUserStorage(a.u.id,textBytes(b.title,b.content));const[n]=await db.insert(notes).values({workspaceId:nb.workspaceId,notebookId:nb.id,folderId:b.folder_id??null,title:b.title,bodyMd:b.content,tags:b.tags,aiIndex:nb.defaultAiIndex,createdBy:a.u.id,updatedBy:a.u.id}).returning();await db.insert(noteVersions).values({noteId:n.id,version:1,title:n.title,bodyMd:n.bodyMd,editorId:a.u.id,source:"mcp"});// 与 UI 建note 一致：第 1 版也要留档，否则历史缺头
await writeNoteFile({...n,noteId:n.id,bodyMd:n.bodyMd});await rebuildLinks(n.id,n.workspaceId,n.bodyMd);result={id:n.id,version:n.version};}
else if(result===undefined&&name==="update_note"){requireWrite(a);const b=z.object({id:z.string().uuid(),expected_version:zint().positive(),content:z.string().optional(),title:z.string().min(1).max(200).optional(),dry_run:zbool().default(false)}).parse(x),{note:n}=await permission(a,b.id,"edit");if(b.expected_version!==n.version)throw fail("CONFLICT_VERSION","版本冲突",{version:String(n.version)});if(b.dry_run)result={dry_run:true,id:n.id,title:n.title,current_version:n.version,next_version:n.version+1,changes:{title:b.title!==undefined&&b.title!==n.title,content:b.content!==undefined&&b.content!==n.bodyMd},required_execution:{expected_version:n.version}};else result=await commitNote(a,n,b.title??n.title,b.content??n.bodyMd,{chargeBytes:Buffer.byteLength(b.content??"","utf8")+Buffer.byteLength(b.title??"","utf8")});}
else if(result===undefined&&name==="append_to_note"){requireWrite(a);const b=z.object({id:z.string().uuid(),expected_version:zint().positive().optional(),content:z.string().min(1),title:z.string().min(1).max(200).optional()}).parse(x);await charge(a,Buffer.byteLength(b.content,"utf8")+Buffer.byteLength(b.title??"","utf8"));let last:unknown;for(let i=0;i<3;i++){const{note:n}=await permission(a,b.id,"edit");if(b.expected_version!==undefined&&b.expected_version!==n.version)throw fail("CONFLICT_VERSION","版本冲突",{version:String(n.version)});try{result=await commitNote(a,n,b.title??n.title,`${n.bodyMd}${n.bodyMd?"\n":""}${b.content}`,{alreadyCharged:true});last=undefined;break;}catch(e){last=e;if(!(e instanceof AppError)||e.code!=="CONFLICT_VERSION"||b.expected_version!==undefined||i===2)throw e;}}if(last)throw last;}
else if(result===undefined&&name==="replace_in_note"){requireWrite(a);const b=z.object({id:z.string().uuid(),expected_version:zint().positive(),old:z.string().min(1),new:z.string(),replace_all:zbool().default(false)}).parse(x),{note:n}=await permission(a,b.id,"edit");if(b.expected_version!==n.version)throw fail("CONFLICT_VERSION","版本冲突",{version:String(n.version)});const occ=countOcc(n.bodyMd,b.old);if(!occ)throw fail("VALIDATION","原文中找不到要替换的片段");if(occ>1&&!b.replace_all)throw fail("VALIDATION","片段出现多次，请传更长的上下文或 replace_all");const bodyMd=b.replace_all?n.bodyMd.split(b.old).join(b.new):n.bodyMd.slice(0,n.bodyMd.indexOf(b.old))+b.new+n.bodyMd.slice(n.bodyMd.indexOf(b.old)+b.old.length);if(bodyMd===n.bodyMd)result={id:n.id,version:n.version,replacements:0};else{const saved=await commitNote(a,n,n.title,bodyMd,{chargeBytes:Buffer.byteLength(b.new,"utf8")});result={...saved,replacements:b.replace_all?occ:1};}}
else if(result===undefined&&name==="move_note"){requireWrite(a,true);const b=z.object({id:z.string().uuid(),expected_version:zint().positive(),notebook_id:z.string().uuid(),folder_id:z.string().uuid().nullable().optional(),dry_run:zbool().default(false)}).parse(x),{note:n}=await permission(a,b.id,"edit"),{notebook:nb}=await nbPermission(a,b.notebook_id,"edit");if(b.expected_version!==n.version)throw fail("CONFLICT_VERSION","版本冲突",{version:String(n.version)});if(b.dry_run)result={dry_run:true,id:n.id,title:n.title,current_version:n.version,from:{notebook_id:n.notebookId,folder_id:n.folderId??null},to:{notebook_id:nb.id,folder_id:b.folder_id??null},required_execution:{expected_version:n.version}};else result=await relocateNote({note:n,targetNotebook:nb,folderId:b.folder_id??null,actorId:a.u.id,expectedVersion:b.expected_version});}
else if(result===undefined&&name==="add_tags"){requireWrite(a,true);const b=z.object({id:z.string().uuid(),tags:z.array(z.string().min(1).max(50)).max(50)}).parse(x),{note:n}=await permission(a,b.id,"edit"),merged=[...new Set([...(n.tags as string[]),...b.tags])].slice(0,50);await charge(a,Buffer.byteLength(JSON.stringify(b.tags)));const[saved]=await db.update(notes).set({tags:merged,version:n.version+1,updatedBy:a.u.id,updatedAt:new Date()}).where(eq(notes.id,n.id)).returning();result={id:saved.id,version:saved.version,tags:merged};}
else if(result===undefined&&name==="trash_note"){requireWrite(a,true);if(!a.t.allowDelete)throw fail("FORBIDDEN","钥匙未授权删除");const b=z.object({id:z.string().uuid(),expected_version:zint().positive(),dry_run:zbool().default(false)}).parse(x),{note:n}=await permission(a,b.id,"edit");if(b.expected_version!==n.version)throw fail("CONFLICT_VERSION","版本冲突",{version:String(n.version)});if(b.dry_run)result={dry_run:true,id:n.id,title:n.title,current_version:n.version,from:{notebook_id:n.notebookId,folder_id:n.folderId??null},effect:"move_to_trash",required_execution:{expected_version:n.version}};else{const[saved]=await db.update(notes).set({trashedAt:new Date(),trashedBy:a.u.id,trashBatchId:crypto.randomUUID()}).where(and(eq(notes.id,n.id),eq(notes.version,b.expected_version),isNull(notes.trashedAt))).returning({id:notes.id});if(!saved)throw fail("CONFLICT_VERSION","版本冲突",{version:String(n.version)});result={id:saved.id};}}
else if(result===undefined&&name==="post_to_feed"){const b=z.object({body:z.string().min(1).max(5000),scope:z.enum(["workspace","public"]).default("workspace"),note_id:z.string().uuid().optional(),workspace_id:z.string().uuid().optional(),confirm_public:zbool().default(false),dry_run:zbool().default(false),client_request_id:z.string().uuid().optional()}).parse(x);
 if(b.scope==="public"&&!a.t.feedPublic)throw fail("FORBIDDEN","钥匙未授权发广场动态");
 if(b.scope==="workspace"&&!a.t.feedWorkspace)throw fail("FORBIDDEN","钥匙未授权发工作区动态");
 if(b.note_id)await permission(a,b.note_id,"read");
 const feedWs=b.scope==="workspace"?pickWorkspace(a,b.workspace_id):null;
 const[ws2]=feedWs?await db.select().from(workspaces).where(eq(workspaces.id,feedWs)):[];
 if(b.scope==="workspace"&&ws2?.frozen)throw fail("FORBIDDEN","工作区已冻结，暂时只读");
 if(b.dry_run)result={dry_run:true,scope:b.scope,workspace_id:feedWs,note_id:b.note_id??null,body_preview:b.body.slice(0,240),required_confirmation:b.scope==="public"?{confirm_public:true}:null};
 else if(b.scope==="public"&&!b.confirm_public)throw fail("CONFIRMATION_REQUIRED","公开发布必须显式传 confirm_public=true");
 // MCP 也是发帖入口，跟 HTTP 那条走同一遍审核（设计 18 §1）。这里不审，等于给自动化留了个绕过口子。
 if(result===undefined){const mscope=b.scope==="public"?"square":"circle";
 const msettings=await instanceConfig();const held=moderationOn(msettings,mscope);
 const[post]=await db.insert(posts).values({authorUserId:a.u.id,workspaceId:b.scope==="workspace"?feedWs:null,visibility:b.scope==="public"?"public":"workspace",body:b.body,noteId:b.note_id??null,status:held?"pending_review":"visible"}).returning();
 const mod=held?await queueReview({targetType:"post",targetId:post.id,scope:mscope,workspaceId:post.workspaceId,authorUserId:a.u.id,snapshot:b.body}):{held:false,queued:false,message:null};
 result={id:post.id,scope:b.scope,status:post.status,moderation_message:mod.message};}}
else if(result===undefined&&(name==="list_tasks"||name==="list_events")){const kind=name==="list_tasks"?"task":"event";
 const b=z.object({from:z.string().datetime().optional(),to:z.string().datetime().optional(),status:z.enum(["open","done","all"]).default(name==="list_tasks"?"open":"all"),assignee:z.string().max(40).optional(),include_inbox:zbool().default(true),workspace_id:z.string().uuid().optional(),limit:zint().min(1).max(200).default(200),cursor:z.string().optional()}).parse(x);
 // 默认窗口「今天起 14 天」（架构 03 §5）：从当地日历日 00:00 起，否则今天早些时候到期的会被切掉
 const from=b.from?new Date(b.from):startOfLocalDay(new Date(),DEFAULT_TZ),to=b.to?new Date(b.to):new Date(from.getTime()+14*86400000);
 if(to<=from)throw fail("VALIDATION","结束时间必须晚于开始时间");
 if(to.getTime()-from.getTime()>400*86400000)throw fail("VALIDATION","一次最多查 400 天");
 const calWs=scopeIds(a,b.workspace_id);
 let rows=(await db.select().from(calendarItems).where(and(inArray(calendarItems.workspaceId,calWs),eq(calendarItems.kind,kind),isNull(calendarItems.trashedAt))));
 if(b.assignee&&b.assignee!=="any"){const handle=b.assignee==="me"?a.u.handle:b.assignee.replace(/^[+@]+/,"");const[who]=await db.select().from(users).where(eq(users.handle,handle));rows=rows.filter(r=>!!who&&r.assigneeUserId===who.id);}
 const visible=await visibleCalendarItems(a,rows);
 const ovs=visible.length?await db.select().from(calendarOverrides).where(inArray(calendarOverrides.itemId,visible.map(r=>r.id))):[];
 const byItem=new Map<string,Array<typeof calendarOverrides.$inferSelect>>();for(const o of ovs)byItem.set(o.itemId,[...(byItem.get(o.itemId)??[]),o]);
 const noteIds=[...new Set(visible.map(r=>r.sourceNoteId).filter((v):v is string=>!!v))];
 const titles=new Map((noteIds.length?await db.select({id:notes.id,title:notes.title}).from(notes).where(inArray(notes.id,noteIds)):[]).map(n=>[n.id,n.title]));
 const dto=(r:typeof calendarItems.$inferSelect,at:Date|null,occ:Date|null,status:string)=>({id:r.id,title:r.title,kind:r.kind,status,priority:r.priority,all_day:r.allDay,[kind==="task"?"due_at":"starts_at"]:at,ends_at:r.endsAt,occurrence_start:occ,timezone:r.timezone,recurring:!!r.rrule,rrule:r.rrule,source:r.source,link_state:r.linkState,source_note_id:r.sourceNoteId,note_title:r.sourceNoteId?titles.get(r.sourceNoteId)??null:null,url:`${env.publicUrl}/w/${r.workspaceId}/calendar?item=${r.id}`});
 const out=visible.filter(r=>r.startsAt??r.dueAt).flatMap(r=>occurrencesOf(r,byItem.get(r.id)??[],from,to).map(o=>dto(r,o.start,o.occurrenceStart,o.status)));
 // 收件箱（无期限的待办）默认一起给：问「我要做什么」的人不会希望漏掉没排期的那些
 if(kind==="task"&&b.include_inbox)out.push(...visible.filter(r=>!r.startsAt&&!r.dueAt).map(r=>dto(r,null,null,r.status)));
 const ctx=await cursorContext(a,name,{from:from.toISOString(),to:to.toISOString(),status:b.status,assignee:b.assignee??null,include_inbox:b.include_inbox,workspace_id:b.workspace_id??null}),page=pageByCursor({...ctx,cursor:b.cursor,limit:b.limit,items:out.filter(r=>b.status==="all"||r.status===b.status),keyOf:r=>{const at=r.occurrence_start??(kind==="task"?r.due_at:r.starts_at);return[at instanceof Date?at.toISOString():at?String(at):"",r.id,r.occurrence_start instanceof Date?r.occurrence_start.toISOString():r.occurrence_start?String(r.occurrence_start):""];},directions:["asc","asc","asc"]});result=page;}
else if(result===undefined&&name==="today"){
  const from=startOfLocalDay(new Date(),DEFAULT_TZ),to=new Date(from.getTime()+86400000);
  const w=wallParts(from,DEFAULT_TZ);
  const b=z.object({workspace_id:z.string().uuid().optional()}).parse(x);
   const todayWs=scopeIds(a,b.workspace_id);
   const rows=await db.select().from(calendarItems).where(and(inArray(calendarItems.workspaceId,todayWs),isNull(calendarItems.trashedAt)));
  const visible=await visibleCalendarItems(a,rows);
  const ovs=visible.length?await db.select().from(calendarOverrides).where(inArray(calendarOverrides.itemId,visible.map(r=>r.id))):[];
  const byItem=new Map<string,Array<typeof calendarOverrides.$inferSelect>>();for(const o of ovs)byItem.set(o.itemId,[...(byItem.get(o.itemId)??[]),o]);
  const noteIds=[...new Set(visible.map(r=>r.sourceNoteId).filter((v):v is string=>!!v))];
  const titles=new Map((noteIds.length?await db.select({id:notes.id,title:notes.title}).from(notes).where(inArray(notes.id,noteIds)):[]).map(n=>[n.id,n.title]));
  const dto=(r:typeof calendarItems.$inferSelect,at:Date|null,occ:Date|null,status:string)=>({id:r.id,title:r.title,kind:r.kind,status,priority:r.priority,all_day:r.allDay,due_at:r.kind==="task"?at:undefined,starts_at:r.kind==="event"?at:undefined,ends_at:r.endsAt,occurrence_start:occ,timezone:r.timezone,recurring:!!r.rrule,source:r.source,link_state:r.linkState,source_note_id:r.sourceNoteId,note_title:r.sourceNoteId?titles.get(r.sourceNoteId)??null:null,url:`${env.publicUrl}/w/${r.workspaceId}/calendar?item=${r.id}`});
  const items=visible.filter(r=>r.startsAt??r.dueAt).flatMap(r=>occurrencesOf(r,byItem.get(r.id)??[],from,to).map(o=>dto(r,o.start,o.occurrenceStart,o.status)));
  const overdue=visible.filter(r=>r.kind==="task"&&r.status==="open"&&r.dueAt&&r.dueAt<from&&!r.rrule).map(r=>dto(r,r.dueAt,null,r.status));
  result={date:`${w.y}-${String(w.m).padStart(2,"0")}-${String(w.d).padStart(2,"0")}`,timezone:DEFAULT_TZ,items,overdue,notes:await listRecentNotes({workspaceIds:todayWs,since:from,limit:50,accept:id=>acceptNote(a!,id)})};
}else if(result===undefined&&name==="create_task"){requireWrite(a);
 // 刻意只让建独立任务：否则一把「只读笔记」的钥匙能靠建任务绕道改正文（设计 16 §6.3）
 const b=z.object({title:z.string().min(1).max(200),due_at:z.string().datetime().nullish(),all_day:zbool().default(false),priority:zint().min(0).max(3).default(0),note:z.string().max(2000).default(""),workspace_id:z.string().uuid().optional(),client_request_id:z.string().uuid().optional()}).parse(x);
  const taskWs=pickWorkspace(a,b.workspace_id);
 const[ws3]=await db.select().from(workspaces).where(eq(workspaces.id,taskWs));
 if(ws3?.frozen)throw fail("FORBIDDEN","工作区已冻结，暂时只读");
 const[total]=await db.select({n:count()}).from(calendarItems).where(eq(calendarItems.workspaceId,taskWs));
 if((total?.n??0)>=50000)throw fail("QUOTA","日历项已达上限，请先清理");
 await charge(a,textBytes(b.title,b.note));
 const due=b.due_at?new Date(b.due_at):null;
 const[row]=await db.insert(calendarItems).values({workspaceId:taskWs,kind:"task",title:b.title.trim(),bodyMd:b.note,allDay:b.all_day,dueAt:due,timezone:DEFAULT_TZ,priority:b.priority,source:"mcp",createdBy:a.u.id,updatedBy:a.u.id}).returning();
 result={id:row.id,title:row.title,due_at:row.dueAt,status:row.status,url:`${env.publicUrl}/w/${taskWs}/calendar?item=${row.id}`};}
else if(result===undefined&&name==="complete_task"){requireWrite(a);
 const b=z.object({id:z.string().uuid(),done:zbool().default(true),occurrence_start:z.string().datetime().optional(),dry_run:zbool().default(false)}).parse(x);
 const[item]=await db.select().from(calendarItems).where(eq(calendarItems.id,b.id));
 if(!item||item.trashedAt||!covers(a,item.workspaceId))throw fail("NOT_FOUND","日历项不存在");
 if(!(await visibleCalendarItems(a,[item])).length)throw fail("NOT_FOUND","日历项不存在");
 // 回写正文等于改笔记，所以要按「能编辑这篇笔记」判，而不是只看条目可见
 if(item.source==="note"&&item.sourceNoteId)await permission(a,item.sourceNoteId,"edit");
 const[ws4]=await db.select().from(workspaces).where(eq(workspaces.id,item.workspaceId));
 if(ws4?.frozen)throw fail("FORBIDDEN","工作区已冻结，暂时只读");
 if(b.dry_run)result={dry_run:true,id:item.id,title:item.title,current_status:item.status,target_status:b.done?"done":"open",occurrence_start:b.occurrence_start??null,note_id:item.sourceNoteId??null,note_will_be_written:item.source==="note"&&!!item.sourceNoteId};
 else{await charge(a,textBytes(item.title,""));
 const r=await completeCalendarItem(item,a.u.id,b.done,b.occurrence_start?new Date(b.occurrence_start):undefined,"mcp");
 result={id:item.id,status:r.status,note_written:r.noteWritten,detached:r.detached,note_id:r.noteId};}}
else if(result===undefined)throw fail("VALIDATION","未知工具");
if(idemClaim&&result!==undefined)await finishIdempotent(idemClaim,result);
await db.insert(auditLogs).values({userId:a.u.id,workspaceId:a.workspaceIds[0],actorType:"mcp",actorId:a.t.id,action:`mcp.${name}`,result:"ok",details:{arguments:auditArgs(x)}}).catch(e=>console.warn("mcp 审计写入失败（不影响本次调用）:",e));const sc=result&&typeof result==="object"&&!Array.isArray(result)?result:undefined;return c.json({jsonrpc:"2.0",id,result:{content:[{type:"text",text:JSON.stringify(result)}],...(sc?{structuredContent:sc}:{})}});
}catch(e){
  if(idemClaim)await abortIdempotent(idemClaim).catch(err=>console.warn("MCP 幂等占位清理失败:",err));
  // 未认证必须回 401 且带 WWW-Authenticate，云端客户端靠它发现授权服务器（RFC 9728）
  if(e instanceof AppError&&e.code==="UNAUTHENTICATED")return unauthorized(c,id,e.message);
  const data=e instanceof AppError?{code:e.code,message:e.message,...(e.fields??{})}:e instanceof z.ZodError?{code:"VALIDATION",message:e.issues.map(i=>`${i.path.length?`${i.path.join(".")}：`:""}${i.message}`).join("；")||"参数不合法"}:{code:"INTERNAL",message:e instanceof Error?e.message:String(e)};
   if(a)await db.insert(auditLogs).values({userId:a.u.id,workspaceId:a.workspaceIds[0],actorType:"mcp",actorId:a.t.id,action:`mcp.${name||"request"}`,result:"error",details:{message:data.message,code:data.code}}).catch(err=>console.warn("mcp 审计写入失败（不影响本次调用）:",err));return c.json({jsonrpc:"2.0",id,error:{code:-32000,message:data.message,data}});}});
