import { Hono } from "hono";
import { and, eq } from "drizzle-orm";
import { z } from "zod";
import { fail } from "@kb/shared";
import { db } from "../db/client.ts";
import { mcpTokens, users, workspaceInvites, workspaceMembers, workspaces } from "../db/schema.ts";
import { ok } from "../http.ts";
import { currentUser } from "../lib/session.ts";
import { secureToken, tokenHash } from "../lib/tokens.ts";
import { memberRole,migratePrivateNotebooks } from "../lib/workspace.ts";

export const memberRoutes = new Hono();
async function userRequired(c: Parameters<typeof currentUser>[0]) { const u = await currentUser(c); if (!u) throw fail("UNAUTHENTICATED", "未登录"); return u; }
async function manage(c: Parameters<typeof currentUser>[0], wsId: string) { const u = await userRequired(c); const role = await memberRole(wsId, u.id); if (role !== "owner" && role !== "admin") throw fail("FORBIDDEN", "只有工作区管理员可管理成员"); return u; }

memberRoutes.get("/workspaces/:id/members", async c => {
  const u = await userRequired(c); const wsId = c.req.param("id"); if (!(await memberRole(wsId, u.id))) throw fail("FORBIDDEN", "不是工作区成员");
  const rows = await db.select({ userId: users.id, handle: users.handle, displayName: users.displayName, email: users.email, status: users.status, role: workspaceMembers.role, joinedAt: workspaceMembers.createdAt }).from(workspaceMembers).innerJoin(users, eq(users.id, workspaceMembers.userId)).where(eq(workspaceMembers.workspaceId, wsId));
  const [ws] = await db.select().from(workspaces).where(eq(workspaces.id, wsId)); return ok(c, { kind: ws?.kind, members: rows });
});
memberRoutes.post("/workspaces/:id/members", async c => {
  await manage(c, c.req.param("id")); const wsId = c.req.param("id"); const [ws] = await db.select().from(workspaces).where(eq(workspaces.id, wsId)); if (!ws) throw fail("NOT_FOUND", "工作区不存在"); if (ws.kind === "personal") throw fail("FORBIDDEN", "个人工作区不能添加成员");
  const body = z.object({ handle: z.string(), role: z.enum(["admin", "editor", "viewer"]) }).parse(await c.req.json()); const [target] = await db.select().from(users).where(eq(users.handle, body.handle)); if (!target || target.status !== "active") throw fail("NOT_FOUND", "未找到可添加的用户");
  await db.insert(workspaceMembers).values({ workspaceId: wsId, userId: target.id, role: body.role }).onConflictDoUpdate({ target: [workspaceMembers.workspaceId, workspaceMembers.userId], set: { role: body.role } }); return ok(c, {});
});
memberRoutes.patch("/workspaces/:id/members/:userId", async c => {
  const actor = await manage(c, c.req.param("id")); const wsId = c.req.param("id"), userId = c.req.param("userId"); const body = z.object({ role: z.enum(["admin", "editor", "viewer"]) }).parse(await c.req.json()); const [ws] = await db.select().from(workspaces).where(eq(workspaces.id, wsId)); if (!ws) throw fail("NOT_FOUND", "工作区不存在"); if (userId === ws.ownerId) throw fail("FORBIDDEN", "请先转让工作区所有权"); if (actor.id === userId && body.role === "viewer") throw fail("FORBIDDEN", "不能把自己降为只读成员"); await db.update(workspaceMembers).set({ role: body.role }).where(and(eq(workspaceMembers.workspaceId, wsId), eq(workspaceMembers.userId, userId))); return ok(c, {});
});
memberRoutes.post("/workspaces/:id/transfer",async c=>{const actor=await userRequired(c);const wsId=c.req.param("id");const body=z.object({newOwnerUserId:z.string().uuid()}).parse(await c.req.json());const [ws]=await db.select().from(workspaces).where(eq(workspaces.id,wsId));if(!ws)throw fail("NOT_FOUND","工作区不存在");if(ws.kind==="personal")throw fail("FORBIDDEN","个人工作区不能转让");if(ws.ownerId!==actor.id)throw fail("FORBIDDEN","只有当前 Owner 可以转让");if(body.newOwnerUserId===actor.id)throw fail("VALIDATION","新 Owner 不能是自己");const [target]=await db.select().from(workspaceMembers).where(and(eq(workspaceMembers.workspaceId,wsId),eq(workspaceMembers.userId,body.newOwnerUserId)));if(!target)throw fail("VALIDATION","新 Owner 必须已经是工作区成员");await db.transaction(async tx=>{await tx.update(workspaceMembers).set({role:"admin"}).where(and(eq(workspaceMembers.workspaceId,wsId),eq(workspaceMembers.userId,actor.id)));await tx.update(workspaceMembers).set({role:"owner"}).where(and(eq(workspaceMembers.workspaceId,wsId),eq(workspaceMembers.userId,body.newOwnerUserId)));await tx.update(workspaces).set({ownerId:body.newOwnerUserId}).where(eq(workspaces.id,wsId));});return ok(c,{ownerId:body.newOwnerUserId});});

memberRoutes.delete("/workspaces/:id/members/:userId", async c => {
  const actor = await manage(c, c.req.param("id")); const wsId = c.req.param("id"), userId = c.req.param("userId"); const [ws] = await db.select().from(workspaces).where(eq(workspaces.id, wsId)); if (!ws) throw fail("NOT_FOUND", "工作区不存在"); if (ws.kind === "personal" || userId === ws.ownerId) throw fail("FORBIDDEN", "不能移除个人工作区或工作区 Owner"); if (actor.id === userId) throw fail("FORBIDDEN", "管理员不能在成员页移除自己"); const migratedNotebooks=await migratePrivateNotebooks(userId,wsId);await db.transaction(async tx=>{await tx.delete(workspaceMembers).where(and(eq(workspaceMembers.workspaceId, wsId), eq(workspaceMembers.userId, userId)));await tx.update(mcpTokens).set({status:"revoked"}).where(and(eq(mcpTokens.workspaceId,wsId),eq(mcpTokens.userId,userId)));await tx.update(workspaceInvites).set({status:"revoked"}).where(and(eq(workspaceInvites.workspaceId,wsId),eq(workspaceInvites.createdBy,userId),eq(workspaceInvites.status,"active")));}); return ok(c, {migratedNotebooks});
});
memberRoutes.post("/workspaces/:id/invites", async c => {
  const actor = await manage(c, c.req.param("id")); const wsId = c.req.param("id"); const [ws] = await db.select().from(workspaces).where(eq(workspaces.id, wsId)); if (!ws || ws.kind === "personal") throw fail("FORBIDDEN", "个人工作区不能邀请成员"); const body = z.object({ role: z.enum(["admin", "editor", "viewer"]), expiresInDays: z.number().int().min(1).max(90).default(7), maxUses: z.number().int().min(1).max(100).nullable().default(1) }).parse(await c.req.json()); const token = secureToken(); const [invite] = await db.insert(workspaceInvites).values({ tokenHash: tokenHash(token), tokenPrefix: token.slice(0, 8), workspaceId: wsId, role: body.role, expiresAt: new Date(Date.now() + body.expiresInDays * 86400000), maxUses: body.maxUses, createdBy: actor.id }).returning(); return ok(c, { id: invite.id, token, url: `/invite/${token}` }, 201);
});
memberRoutes.get("/invites/:token", async c => { const [i] = await db.select().from(workspaceInvites).where(eq(workspaceInvites.tokenHash, tokenHash(c.req.param("token")))); if (!i || i.status !== "active" || i.expiresAt.getTime() <= Date.now() || (i.maxUses && i.usedCount >= i.maxUses)) throw fail("NOT_FOUND", "邀请不存在或已失效"); const [ws] = await db.select().from(workspaces).where(eq(workspaces.id, i.workspaceId)); return ok(c, { workspace: ws?.name, role: i.role, expiresAt: i.expiresAt }); });
memberRoutes.post("/invites/:token/accept", async c => { const u = await userRequired(c);const hash=tokenHash(c.req.param("token"));const workspaceId=await db.transaction(async tx=>{const [i]=await tx.select().from(workspaceInvites).where(eq(workspaceInvites.tokenHash,hash)).for("update");if(!i||i.status!=="active"||i.expiresAt.getTime()<=Date.now()||(i.maxUses&&i.usedCount>=i.maxUses))throw fail("NOT_FOUND","邀请不存在或已失效");const[ws]=await tx.select().from(workspaces).where(eq(workspaces.id,i.workspaceId));if(!ws||ws.kind==="personal")throw fail("NOT_FOUND","工作区不存在");const existing=await tx.select().from(workspaceMembers).where(and(eq(workspaceMembers.workspaceId,ws.id),eq(workspaceMembers.userId,u.id)));if(!existing.length){await tx.insert(workspaceMembers).values({workspaceId:ws.id,userId:u.id,role:i.role});const used=i.usedCount+1;await tx.update(workspaceInvites).set({usedCount:used,status:i.maxUses&&used>=i.maxUses?"exhausted":"active"}).where(eq(workspaceInvites.id,i.id));}return ws.id;});return ok(c,{workspaceId}); });
